const DATA = {
  pro: [
    { de: "Sollen wir uns am See treffen?", t:{ ua:"Зустрінемось біля озера?", tr:"Göl kenarında buluşalım mı?", so:"Harada ku kulannaa?", fa:"کنار دریاچه همدیگر را ببینیم؟", af:"Sal ons by die meer ontmoet?" }},
    { de: "Wie wäre es mit einem Picknick am Wochenende?", t:{ ua:"Як щодо пікніка на вихідних?", tr:"Hafta sonu piknik yapalım mı?", so:"Dhammaadka usbuuca picnic?", fa:"آخر هفته پیک‌نیک چطور؟", af:"’n Piekniek oor die naweek?" }},
    { de: "Lass uns etwas Einfaches planen.", t:{ ua:"Давай щось просте.", tr:"Basit bir şey planlayalım.", so:"Aan wax fudud qorshayno.", fa:"بیایید ساده برنامه‌ریزی کنیم.", af:"Kom ons hou dit eenvoudig." }},
    { de: "Ich schlage vor, wir treffen uns nach der Arbeit.", t:{ ua:"Пропоную після роботи.", tr:"İşten sonra buluşalım.", so:"Shaqada kadib aan kulanno.", fa:"بعد از کار ملاقات کنیم.", af:"Kom ons ontmoet ná werk." }},
    { de: "Wir könnten gemeinsam kochen.", t:{ ua:"Можемо разом готувати.", tr:"Birlikte yemek yapabiliriz.", so:"Wada karino.", fa:"با هم آشپزی کنیم.", af:"Ons kan saam kook." }},
    { de: "Vielleicht machen wir es bei mir.", t:{ ua:"Можливо, у мене.", tr:"Belki bende.", so:"Malaha gurigayga.", fa:"شاید خانه من.", af:"Miskien by my." }},
    { de: "Ich bringe Getränke mit.", t:{ ua:"Я принесу напої.", tr:"İçecekleri ben getiririm.", so:"Cabitaan waan keenaa.", fa:"من نوشیدنی می‌آورم.", af:"Ek bring drankies." }},
    { de: "Wollen wir uns am Treffpunkt beim Bahnhof sehen?", t:{ ua:"Зустрінемось біля Treffpunkt на вокзалі?", tr:"İstasyondaki Treffpunkt’te buluşalım mı?", so:"Ma ku kulannaa Treffpunkt-ka?", fa:"در Treffpunkt ایستگاه همدیگر را ببینیم؟", af:"Ontmoet ons by die Treffpunkt by die stasie?" }},
    { de: "Vielleicht nach der Arbeit ein Bier?", t:{ ua:"Може пиво після роботи?", tr:"İşten sonra bir bira?", so:"Shaqada kadib biir?", fa:"بعد از کار یک آبجو؟", af:"’n Bier ná werk?" }},
    { de: "Lass uns das Wetter ausnutzen.", t:{ ua:"Скористаймось гарною погодою.", tr:"Havayı değerlendirelim.", so:"Cimilada ka faa’iidaysanno.", fa:"از هوا استفاده کنیم.", af:"Kom ons benut die weer." }},
    { de: "Wir könnten grillieren.", t:{ ua:"Можемо посмажити на грилі.", tr:"Mangal yapabiliriz.", so:"Waan dubi karnaa.", fa:"می‌توانیم گریل کنیم.", af:"Ons kan braai." }},
    { de: "Hast du Lust auf einen Spaziergang?", t:{ ua:"Хочеш прогулятись?", tr:"Yürüyüşe var mısın?", so:"Socod ma rabtaa?", fa:"حوصله پیاده‌روی داری؟", af:"Lus vir ’n stap?" }},
    { de: "Sollen wir zusammen ÖV fahren?", t:{ ua:"Поїдемо разом ÖV?", tr:"Toplu taşımayla gidelim mi?", so:"Gaadiidka dadweynaha wada raacnaa?", fa:"با حمل‌ونقل عمومی برویم؟", af:"Gebruik ons saam openbare vervoer?" }},
    { de: "Vielleicht ein Kaffee in der Stadt?", t:{ ua:"Може кава в місті?", tr:"Şehirde kahve?", so:"Qaxwo magaalada?", fa:"قهوه در شهر؟", af:"’n Koffie in die stad?" }},
    { de: "Wollen wir das spontan entscheiden?", t:{ ua:"Вирішимо спонтанно?", tr:"Spontane karar verelim mi?", so:"Si kedis ah u go’aaminnaa?", fa:"خودجوش تصمیم بگیریم؟", af:"Besluit ons spontaan?" }},
    { de: "Lass uns etwas Kleines machen.", t:{ ua:"Зробімо щось невелике.", tr:"Küçük bir şey yapalım.", so:"Wax yar sameyno.", fa:"کار کوچکی بکنیم.", af:"Kom ons doen iets kleins." }},
    { de: "Wie wäre es heute Abend?", t:{ ua:"Як щодо сьогодні ввечері?", tr:"Bu akşam nasıl?", so:"Caawa sidee?", fa:"امشب چطور؟", af:"Hoe lyk vanaand?" }},
    { de: "Hast du morgen Zeit?", t:{ ua:"Маєш час завтра?", tr:"Yarın vaktin var mı?", so:"Berri waqti ma haysaa?", fa:"فردا وقت داری؟", af:"Het jy môre tyd?" }},
    { de: "Sollen wir etwas zusammen unternehmen?", t:{ ua:"Зробимо щось разом?", tr:"Birlikte bir şey yapalım mı?", so:"Wax wada sameynaa?", fa:"کاری را با هم انجام دهیم؟", af:"Doen ons iets saam?" }},
    { de: "Vielleicht nur kurz.", t:{ ua:"Може ненадовго.", tr:"Kısa bir süre.", so:"Wax yar.", fa:"کوتاه.", af:"Net kortliks." }},
    { de: "Ich hätte eine Idee.", t:{ ua:"У мене є ідея.", tr:"Bir fikrim var.", so:"Fikir ayaan hayaa.", fa:"یک ایده دارم.", af:"Ek het ’n idee." }},
    { de: "Wollen wir es entspannt halten?", t:{ ua:"Зробимо це спокійно?", tr:"Rahat tutalım mı?", so:"Si deggan?", fa:"آرام نگه داریم؟", af:"Hou ons dit rustig?" }},
    { de: "Vielleicht am Fluss entlang.", t:{ ua:"Можливо вздовж річки.", tr:"Nehir boyunca.", so:"Webiga agtiisa.", fa:"کنار رودخانه.", af:"Langs die rivier." }},
    { de: "Vielleicht in den Park gehen?", t:{ ua:"Може підемо в парк?", tr:"Parkta buluşalım mı?", so:"Beerta aan aadno?", fa:"شاید به پارک برویم؟", af:"Miskien na die park?" }},
    { de: "Lass uns eine Runde spazieren.", t:{ ua:"Прогуляємося.", tr:"Bir tur yürüyelim.", so:"Socod sameyno.", fa:"یک دور قدم بزنیم.", af:"Kom ons stap 'n bietjie." }},
    { de: "Wollen wir uns auf einen Drink treffen?", t:{ ua:"Зустрінемось на напій?", tr:"Bir içki için buluşalım mı?", so:"Ma cabitaan kulan?", fa:"برای یک نوشیدنی ملاقات کنیم؟", af:"Ontmoet ons vir ’n drink?" }},
    { de: "Vielleicht bei mir im Garten.", t:{ ua:"Можливо у мене в саду.", tr:"Belki bahçemde.", so:"Malaha beerta gurigayga.", fa:"شاید در باغ من.", af:"Miskien in my tuin." }},
    { de: "Ich hätte Lust auf Spieleabend.", t:{ ua:"Хочу вечір ігор.", tr:"Oyun gecesi isterim.", so:"Waxaan rabaa habeen ciyaaro.", fa:"دوست دارم شب بازی داشته باشیم.", af:"Ek het lus vir ’n speletjiesaand." }},
    { de: "Sollen wir etwas Kochen?", t:{ ua:"Щось приготувати?", tr:"Bir şey pişirelim mi?", so:"Wax cuno karno?", fa:"چیزی بپزیم؟", af:"Kook ons iets?" }},
    { de: "Wie wäre es mit einem Filmabend?", t:{ ua:"Може кіно ввечері?", tr:"Film gecesi nasıl?", so:"Filim habeen?", fa:"شب فیلم چطور؟", af:"’n Fliek-aand?" }},
    { de: "Vielleicht draußen essen?", t:{ ua:"Може поїсти на вулиці?", tr:"Dışarıda yemek?", so:"Bannaanka wax cuno?", fa:"شاید بیرون غذا بخوریم؟", af:"Miskien eet buite?" }},
    { de: "Lass uns etwas Neues ausprobieren.", t:{ ua:"Спробуємо щось нове.", tr:"Yeni bir şey deneyelim.", so:"Wax cusub isku dayno.", fa:"چیزی جدید امتحان کنیم.", af:"Kom ons probeer iets nuuts." }},
    { de: "Sollen wir zusammen Musik hören?", t:{ ua:"Слухати музику разом?", tr:"Birlikte müzik dinleyelim mi?", so:"Ma wada dhageysano muusig?", fa:"با هم موسیقی گوش دهیم؟", af:"Luister ons saam na musiek?" }},
    { de: "Vielleicht eine kleine Wanderung?", t:{ ua:"Можливо невеликий похід?", tr:"Küçük bir yürüyüş?", so:"Socod yar?", fa:"یک پیاده‌روی کوتاه؟", af:"’n Klein stap?" }},
    { de: "Lass uns spontan entscheiden.", t:{ ua:"Вирішимо спонтанно.", tr:"Spontane karar verelim.", so:"Si kedis ah u go’aamino.", fa:"به صورت خودجوش تصمیم بگیریم.", af:"Besluit ons spontaan." }},
    { de: "Wollen wir etwas Sport machen?", t:{ ua:"Зайнятися спортом?", tr:"Spor yapalım mı?", so:"Isboort sameyno?", fa:"ورزش کنیم؟", af:"Doen ons sport?" }},
    { de: "Vielleicht ins Museum gehen?", t:{ ua:"Може в музей?", tr:"Müzeye gidelim mi?", so:"Muzee tagno?", fa:"به موزه برویم؟", af:"Miskien na die museum?" }},
    { de: "Ich hätte Lust auf Eis.", t:{ ua:"Хочу морозиво.", tr:"Dondurma isterim.", so:"Waxaan rabaa baraf macaan.", fa:"دوست دارم بستنی بخورم.", af:"Ek het lus vir roomys." }},
    { de: "Sollen wir zusammen einkaufen?", t:{ ua:"Піти разом за покупками?", tr:"Birlikte alışverişe gidelim mi?", so:"Ma wada wax iibsanno?", fa:"با هم خرید کنیم؟", af:"Gaan ons saam inkopies doen?" }},
    { de: "Vielleicht ein Picknick im Park?", t:{ ua:"Пікнік у парку?", tr:"Parkta piknik?", so:"Picknick beerta?", fa:"پیک‌نیک в парку?", af:"’n Piekniek in die park?" }},
    { de: "Wie wäre es mit einem Abendspaziergang?", t:{ ua:"Вечірня прогулянка?", tr:"Akşam yürüyüşü?", so:"Socod habeen?", fa:"پیاده‌روی شبانه چطور؟", af:"’n Aandstap?" }},
    { de: "Lass uns spontan etwas unternehmen.", t:{ ua:"Зробимо щось спонтанно.", tr:"Spontane bir şey yapalım.", so:"Wax si kedis ah sameyno.", fa:"چیزی خودجوش انجام دهیم.", af:"Kom ons doen iets spontaan." }},
    { de: "Vielleicht einen Ausflug machen?", t:{ ua:"Може зробимо поїздку?", tr:"Bir gezi yapalım mı?", so:"Safar yar sameyno?", fa:"یک سفر کوتاه؟", af:"Miskien ’n uitstappie?" }},
    { de: "Wollen wir zusammen kochen lernen?", t:{ ua:"Навчитися готувати разом?", tr:"Birlikte yemek yapmayı öğrenelim mi?", so:"Ma wada karno baranno?", fa:"با هم آشپزی یاد بگیریم؟", af:"Leer ons saam kook?" }},
    { de: "Ich hätte Lust auf einen Kaffee.", t:{ ua:"Хочу кави.", tr:"Kahve isterim.", so:"Waxaan rabaa qaxwo.", fa:"دوست دارم قهوه بخورم.", af:"Ek het lus vir koffie." }},
    { de: "Vielleicht ein Abendessen planen?", t:{ ua:"Плануємо вечерю?", tr:"Akşam yemeği planlayalım mı?", so:"Habeen cunto qorshayno?", fa:"شام را برنامه‌ریزی کنیم؟", af:"Plan ons ’n aandete?" }},
    { de: "Sollen wir zusammen Sport treiben?", t:{ ua:"Займатися спортом разом?", tr:"Birlikte spor yapalım mı?", so:"Isboort wada sameyno?", fa:"با هم ورزش کنیم؟", af:"Doen ons saam sport?" }},
    { de: "Vielleicht einen Film schauen?", t:{ ua:"Подивимося фільм?", tr:"Film izleyelim mi?", so:"Filim daawanno?", fa:"فیلم ببینیم؟", af:"Kyk ons ’n fliek?" }},
    { de: "Lass uns eine Runde quatschen.", t:{ ua:"Поговоримо трохи.", tr:"Biraz sohbet edelim.", so:"Waan sheekaysannaa.", fa:"کمی گپ بزنیم.", af:"Kom ons gesels 'n bietjie." }},
    { de: "Wollen wir etwas Kreatives machen?", t:{ ua:"Зробимо щось креативне?", tr:"Yaratıcı bir şey yapalım mı?", so:"Wax hal abuur ah sameyno?", fa:"کاری خلاقانه انجام دهیم؟", af:"Doen ons iets kreatief?" }},
    { de: "Vielleicht nur zu zweit?", t:{ ua:"Може тільки вдвох?", tr:"Sadece ikimiz mi?", so:"Kaliya laba?", fa:"فقط دو نفره؟", af:"Miskien net ons twee?" }},
    { de: "Ich hätte Lust auf einen Spaziergang.", t:{ ua:"Хочу прогулянку.", tr:"Yürüyüş yapmak isterim.", so:"Waxaan rabaa socod.", fa:"دوست دارم قدم بزنم.", af:"Ek het lus vir ’n stap." }},
    { de: "Sollen wir etwas Neues probieren?", t:{ ua:"Спробуємо щось нове?", tr:"Yeni bir şey deneyelim mi?", so:"Wax cusub isku dayno?", fa:"چیزی جدید امتحان کنیم؟", af:"Probeer ons iets nuuts?" }},
    { de: "Vielleicht eine kleine Party?", t:{ ua:"Може маленька вечірка?", tr:"Küçük bir parti?", so:"Xaflad yar?", fa:"یک مهمانی کوچک؟", af:"’n Klein partytjie?" }},
    { de: "Lass uns gemeinsam backen.", t:{ ua:"Можемо разом пекти.", tr:"Birlikte fırınlayalım.", so:"Waan wada dubi karnaa.", fa:"با هم بپزیم.", af:"Kom ons saam bak." }},
    { de: "Wollen wir einen Ausflug planen?", t:{ ua:"Сплануємо поїздку?", tr:"Bir gezi planlayalım mı?", so:"Safar qorsheeyo?", fa:"سفر را برنامه‌ریزی کنیم؟", af:"Plan ons ’n uitstappie?" }},
    { de: "Vielleicht nur ein kurzes Treffen?", t:{ ua:"Може коротка зустріч?", tr:"Kısa bir buluşma?", so:"Kulanka gaaban?", fa:"یک ملاقات کوتاه؟", af:"Net ’n kort ontmoeting?" }},
    { de: "Ich hätte Lust auf ein Eis.", t:{ ua:"Хочу морозиво.", tr:"Dondurma isterim.", so:"Waxaan rabaa baraf macaan.", fa:"دوست دارم بستنی.", af:"Ek het lus vir roomys." }},
    { de: "Sollen wir draußen sitzen?", t:{ ua:"Сидіти на вулиці?", tr:"Dışarıda oturalım mı?", so:"Bannaanka fadhiiso?", fa:"در بیرون بنشینیم؟", af:"Sit ons buite?" }},
    { de: "Vielleicht ein kleines Picknick?", t:{ ua:"Може маленький пікнік?", tr:"Küçük bir piknik?", so:"Picknick yar?", fa:"یک پیک‌نیک کوچک؟", af:"’n Klein piekniek?" }},
    { de: "Lass uns spontan etwas essen.", t:{ ua:"З’їмо щось спонтанно.", tr:"Spontane bir şey yiyelim.", so:"Wax si kedis ah wax cuno.", fa:"چیزی خودجوش بخوریم.", af:"Kom ons eet spontaan iets." }},
    { de: "Wie klingt das für dich?", t:{ ua:"Як тобі це звучить?", tr:"Sana nasıl geliyor?", so:"Sidee kula tahay?", fa:"به نظرت چطور است؟", af:"Hoe klink dit vir jou?" }}
  ],
  agr: [
    { de: "Klingt gut.", t: { ua: "Звучить добре.", tr: "Kulağa hoş geliyor.", so: "Waa fiican.", fa: "خوب به نظر می‌رسد.", af: "Klink goed." }},
    { de: "Das passt für mich.", t: { ua: "Мені підходить.", tr: "Bana uyar.", so: "Way ii shaqaysaa.", fa: "برای من مناسب است.", af: "Dit werk vir my." }},
    { de: "Gute Idee.", t: { ua: "Хороша ідея.", tr: "İyi fikir.", so: "Fikir fiican.", fa: "ایده خوب.", af: "Goeie idee." }},
    { de: "Einverstanden.", t: { ua: "Згоден.", tr: "Kabul.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek stem saam." }},
    { de: "Ja, gerne.", t: { ua: "Так, залюбки.", tr: "Evet, memnuniyetle.", so: "Haa, dabcan.", fa: "بله.", af: "Ja, graag." }},
    { de: "Perfekt.", t: { ua: "Ідеально.", tr: "Mükemmel.", so: "Wanaagsan.", fa: "عالی.", af: "Perfek." }},
    { de: "Bin dabei.", t: { ua: "Я з вами.", tr: "Varım.", so: "Waan joogaa.", fa: "هستم.", af: "Ek is in." }},
    { de: "Das macht Sinn.", t: { ua: "Має сенс.", tr: "Mantıklı.", so: "Macno leh.", fa: "منطقی است.", af: "Dit maak sin." }},
    { de: "Natürlich.", t: { ua: "Звичайно.", tr: "Tabii ki.", so: "Dabcan.", fa: "البته.", af: "Natuurlik." }},
    { de: "Abgemacht.", t: { ua: "Домовились.", tr: "Anlaşıldı.", so: "Waa la isku raacay.", fa: "موافقیم.", af: "Afgespreek." }},
    { de: "Sehr gut.", t: { ua: "Дуже добре.", tr: "Çok iyi.", so: "Aad u fiican.", fa: "خیلی خوب.", af: "Baie goed." }},
    { de: "Ich stimme zu.", t: { ua: "Я погоджуюсь.", tr: "Katılıyorum.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek stem saam." }},
    { de: "Klar.", t: { ua: "Зрозуміло.", tr: "Tabii.", so: "Haa.", fa: "حتماً.", af: "Duidelik." }},
    { de: "Einfach super.", t: { ua: "Просто супер.", tr: "Harika.", so: "Aad u fiican.", fa: "فوق‌العاده.", af: "Regtig super." }},
    { de: "Top.", t: { ua: "Відмінно.", tr: "Harika.", so: "Sare.", fa: "عالی.", af: "Top." }},
    { de: "Genau.", t: { ua: "Саме так.", tr: "Tam olarak.", so: "Sida saxda ah.", fa: "دقیقا.", af: "Presies." }},
    { de: "Alles klar.", t: { ua: "Все ясно.", tr: "Her şey tamam.", so: "Wax walba waa cad.", fa: "همه چیز روشن است.", af: "Alles duidelik." }},
    { de: "Ich bin einverstanden.", t: { ua: "Я згоден.", tr: "Kabul ediyorum.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek is saam." }},
    { de: "Passt schon.", t: { ua: "Підходить.", tr: "Uygun.", so: "Waa ku habboon.", fa: "مناسب است.", af: "Dit werk." }},
    { de: "Keine Einwände.", t: { ua: "Без заперечень.", tr: "İtiraz yok.", so: "Dooda ma jirto.", fa: "بدون اعتراض.", af: "Geen besware." }},
    { de: "Alles bestens.", t: { ua: "Все чудово.", tr: "Her şey mükemmel.", so: "Wax walba waa fiican.", fa: "همه چیز عالی.", af: "Alles uitstekend." }},
    { de: "Prima.", t: { ua: "Відмінно.", tr: "Harika.", so: "Wanaagsan.", fa: "عالی.", af: "Prima." }},
    { de: "Super Idee.", t: { ua: "Супер ідея.", tr: "Süper fikir.", so: "Fikir aad u fiican.", fa: "ایده عالی.", af: "Super idee." }},
    { de: "Freut mich.", t: { ua: "Радий.", tr: "Memnun oldum.", so: "Waan ku faraxsanahay.", fa: "خوشحالم.", af: "Ek is bly." }},
    { de: "Natürlich gerne.", t: { ua: "Звичайно.", tr: "Tabii ki.", so: "Dabcan.", fa: "البته.", af: "Natuurlik graag." }},
    { de: "Sehr gerne.", t: { ua: "З великим задоволенням.", tr: "Memnuniyetle.", so: "Si farxad leh.", fa: "با کمال میل.", af: "Baie graag." }},
    { de: "Mit Vergnügen.", t: { ua: "З радістю.", tr: "Ze memnuniyetle.", so: "Farxad ku.", fa: "با خوشحالی.", af: "Met plesier." }},
    { de: "Auf jeden Fall.", t: { ua: "Обов’язково.", tr: "Kesinlikle.", so: "Dabcan.", fa: "حتما.", af: "In elk geval." }},
    { de: "Ich freue mich.", t: { ua: "Радий.", tr: "Sevinçliyim.", so: "Waan ku faraxsanahay.", fa: "خوشحالم.", af: "Ek sien uit daarna." }},
    { de: "Alles in Ordnung.", t: { ua: "Все в порядку.", tr: "Her şey yolunda.", so: "Wax walba waa hagaagsan.", fa: "همه چیز مرتب است.", af: "Alles in orde." }},
    { de: "Passt perfekt.", t: { ua: "Ідеально підходить.", tr: "Mükemmel uyuyor.", so: "Si fiican ayuu u habboon yahay.", fa: "کاملاً مناسب است.", af: "Dit pas perfek." }},
    { de: "Sehr schön.", t: { ua: "Дуже гарно.", tr: "Çok güzel.", so: "Aad u qurux badan.", fa: "خیلی زیبا.", af: "Baie mooi." }},
    { de: "Exzellent.", t: { ua: "Відмінно.", tr: "Mükemmel.", so: "Heer sare.", fa: "عالی.", af: "Uitstekend." }},
    { de: "Absolut.", t: { ua: "Абсолютно.", tr: "Kesinlikle.", so: "Dhab ahaantii.", fa: "کاملاً.", af: "Absoluut." }},
    { de: "Stimmt.", t: { ua: "Правильно.", tr: "Doğru.", so: "Sax.", fa: "درسته.", af: "Stel reg." }},
    { de: "Ich bin dafür.", t: { ua: "Я за.", tr: "Buna katılıyorum.", so: "Waan taageersanahay.", fa: "من موافقم.", af: "Ek is daarvoor." }},
    { de: "Kann ich nur zustimmen.", t: { ua: "Тільки можу погодитись.", tr: "Sadece katılıyorum.", so: "Kaliya waan ku raacsanahay.", fa: "فقط می‌توانم موافقت کنم.", af: "Ek kan net saamstem." }},
    { de: "Das ist richtig.", t: { ua: "Це правильно.", tr: "Bu doğru.", so: "Taas waa sax.", fa: "درسته.", af: "Dit is reg." }},
    { de: "Volle Zustimmung.", t: { ua: "Повна згода.", tr: "Tam onay.", so: "Ogolaansho buuxda.", fa: "کاملاً موافقم.", af: "Volle instemming." }},
    { de: "Absolut richtig.", t: { ua: "Абсолютно правильно.", tr: "Kesinlikle doğru.", so: "Dhab ahaantii sax.", fa: "کاملاً درست.", af: "Absoluut reg." }},
    { de: "Einwandfrei.", t: { ua: "Бездоганно.", tr: "Mükemmel.", so: "Si fiican.", fa: "بی‌نقص.", af: "Onberispelik." }},
    { de: "Richtig so.", t: { ua: "Так правильно.", tr: "Doğru.", so: "Sax sidaas.", fa: "درست است.", af: "Reg so." }},
    { de: "Sehr gut gemacht.", t: { ua: "Дуже добре зроблено.", tr: "Çok iyi yapıldı.", so: "Si fiican loo sameeyey.", fa: "خیلی خوب انجام شد.", af: "Baie goed gedoen." }},
    { de: "Alles bestens erledigt.", t: { ua: "Все відмінно виконано.", tr: "Her şey mükemmel yapıldı.", so: "Wax walba si fiican loo qabtay.", fa: "همه چیز عالی انجام شد.", af: "Alles uitstekend gedoen." }}
  ],
  ref: [
    { de: "Das passt mir leider nicht.", t: { ua: "Мені не підходить.", tr: "Bana uymuyor.", so: "Ii ma shaqaynayso.", fa: "برام مناسب نیست.", af: "Dit pas my ongelukkig nie." }},
    { de: "Ich habe da schon etwas vor.", t: { ua: "Я зайнятий.", tr: "Planım var.", so: "Waxaan hayaa qorshe.", fa: "برنامه دارم.", af: "Ek het reeds planne." }},
    { de: "Vielleicht ein anderes Mal.", t: { ua: "Іншим разом.", tr: "Başka zaman.", so: "Waqti kale.", fa: "یک وقت دیگر.", af: "Miskien ’n ander keer." }},
    { de: "Das wird schwierig.", t: { ua: "Це складно.", tr: "Zor olacak.", so: "Way adkaan doontaa.", fa: "سخت است.", af: "Dit gaan moeilik wees." }},
    { de: "Ich schaffe es zeitlich nicht.", t: { ua: "Не встигаю.", tr: "Vaktim yok.", so: "Waqti ma hayo.", fa: "وقت ندارم.", af: "Ek het nie tyd nie." }},
    { de: "Das passt mir nicht gut.", t: { ua: "Мені зовсім не підходить.", tr: "Hiç uymuyor.", so: "Sikama aha.", fa: "کاملاً مناسب نیست.", af: "Dit pas my glad nie." }},
    { de: "Leider habe ich andere Pläne.", t: { ua: "На жаль, інші плани.", tr: "Maalesef başka planlarım var.", so: "Nasiib darro, qorshayaal kale.", fa: "متأسفانه برنامه دیگری دارم.", af: "Ongelukkig het ek ander planne." }},
    { de: "Ich kann nicht kommen.", t: { ua: "Не можу прийти.", tr: "Gelemem.", so: "Ma imaan karo.", fa: "نمی‌توانم بیایم.", af: "Ek kan nie kom nie." }},
    { de: "Das ist leider nicht möglich.", t: { ua: "На жаль, це неможливо.", tr: "Maalesef mümkün değil.", so: "Nasiib darro ma suurtagal.", fa: "متأسفانه ممکن نیست.", af: "Dit is ongelukkig nie moontlik nie." }},
    { de: "Es tut mir leid, ich kann nicht.", t: { ua: "Вибачте, я не можу.", tr: "Üzgünüm, yapamam.", so: "Waan ka xumahay, ma qaban karo.", fa: "متأسفم، نمی‌توانم.", af: "Ek is jammer, ek kan nie." }},
    { de: "Ich muss absagen.", t: { ua: "Мушу відмінити.", tr: "İptal etmem gerekiyor.", so: "Waan joojinayaa.", fa: "باید لغو کنم.", af: "Ek moet afsê." }},
    { de: "Ich bin verhindert.", t: { ua: "Я зайнятий.", tr: "Müsait değilim.", so: "Ma awoodo.", fa: "مشغولم.", af: "Ek is verhinderd." }},
    { de: "Das klappt leider nicht.", t: { ua: "На жаль, не вийде.", tr: "Maalesef işe yaramıyor.", so: "Nasiib darro ma shaqeynayo.", fa: "متأسفانه درست نمی‌شود.", af: "Dit werk ongelukkig nie." }},
    { de: "Es passt leider nicht.", t: { ua: "На жаль, не підходить.", tr: "Maalesef uymuyor.", so: "Nasiib darro ma habboona.", fa: "متأسفانه مناسب نیست.", af: "Dit pas ongelukkig nie." }},
    { de: "Ich habe leider keine Zeit.", t: { ua: "На жаль, немає часу.", tr: "Maalesef vaktim yok.", so: "Nasiib darro waqti ma hayo.", fa: "متأسفانه وقت ندارم.", af: "Ek het ongelukkig geen tyd nie." }},
    { de: "Leider kann ich nicht teilnehmen.", t: { ua: "На жаль, не можу брати участь.", tr: "Maalesef katılamam.", so: "Nasiib darro ma ka qayb gali karo.", fa: "متأسفانه نمی‌توانم شرکت کنم.", af: "Ongelukkig kan ek nie deelneem nie." }},
    { de: "Es ist mir leider nicht möglich.", t: { ua: "На жаль, для мене це неможливо.", tr: "Maalesef benim için mümkün değil.", so: "Nasiib darro aniga ma suurtagal.", fa: "متأسفانه برای من ممکن نیست.", af: "Dit is ongelukkig nie moontlik vir my nie." }},
    { de: "Ich habe andere Verpflichtungen.", t: { ua: "У мене інші обов’язки.", tr: "Başka yükümlülüklerim var.", so: "Waxqabadyo kale ayaan hayaa.", fa: "متعهد به کار دیگری هستم.", af: "Ek het ander verpligtinge." }},
    { de: "Das passt mir terminlich nicht.", t: { ua: "Не підходить за часом.", tr: "Zamanlama olarak uymuyor.", so: "Waqti ahaan ma habboona.", fa: "زمانش مناسب نیست.", af: "Dit pas nie by my skedule nie." }},
    { de: "Ich bin an diesem Tag beschäftigt.", t: { ua: "В цей день зайнятий.", tr: "O gün meşgulüm.", so: "Maalin taas waxaan ku mashquulsanahay.", fa: "در آن روز مشغولم.", af: "Ek is besig daardie dag." }},
    { de: "Das lässt sich leider nicht einrichten.", t: { ua: "На жаль, не можна організувати.", tr: "Maalesef ayarlanamıyor.", so: "Nasiib darro ma qaban karo.", fa: "متأسفانه نمی‌شود تنظیم کرد.", af: "Dit kan ongelukkig nie gereël word nie." }},
    { de: "Ich bin an diesem Termin verhindert.", t: { ua: "На цей час зайнятий.", tr: "O tarihte müsait değilim.", so: "Waqtigaas ma awoodo.", fa: "در این زمان نمی‌توانم.", af: "Ek is op daardie afspraak verhinderd." }},
    { de: "Ich muss ablehnen.", t: { ua: "Мушу відмовитись.", tr: "Reddetmem gerekiyor.", so: "Waan diidayaa.", fa: "باید رد کنم.", af: "Ek moet weier." }},
    { de: "Das ist nicht machbar.", t: { ua: "Це неможливо.", tr: "Bu mümkün değil.", so: "Ma suurtagal.", fa: "این امکان‌پذیر نیست.", af: "Dit is nie uitvoerbaar nie." }},
    { de: "Ich kann leider nicht zusagen.", t: { ua: "На жаль, не можу погодитись.", tr: "Maalesef onaylayamıyorum.", so: "Nasiib darro ma xaqiijin karo.", fa: "متأسفانه نمی‌توانم موافقت کنم.", af: "Ek kan ongelukkig nie bevestig nie." }},
    { de: "Ich muss es absagen.", t: { ua: "Мушу відмінити.", tr: "İptal etmem gerekiyor.", so: "Waan joojinayaa.", fa: "باید لغو کنم.", af: "Ek moet dit afsê." }},
    { de: "Das ist terminlich ungünstig.", t: { ua: "Час не підходить.", tr: "Zamanlama uygun değil.", so: "Waqti ahaan ma habboona.", fa: "زمان مناسب نیست.", af: "Dit is skeduleer ongunstig." }},
    { de: "Leider passt es nicht.", t: { ua: "На жаль, не підходить.", tr: "Maalesef uymuyor.", so: "Nasiib darro ma habboona.", fa: "متأسفانه مناسب نیست.", af: "Ongelukkig pas dit nie." }},
    { de: "Es kommt mir nicht gelegen.", t: { ua: "Мені це не зручно.", tr: "Bana uygun değil.", so: "Uma habboona.", fa: "برایم مناسب نیست.", af: "Dit pas my nie goed nie." }},
    { de: "Ich habe bereits Pläne.", t: { ua: "В мене вже є плани.", tr: "Zaten planlarım var.", so: "Waxaan hore u qorsheeyay.", fa: "قبلاً برنامه‌ریزی کرده‌ام.", af: "Ek het reeds planne." }},
    { de: "Es passt mir terminlich nicht gut.", t: { ua: "Часом не підходить.", tr: "Zamanlama olarak uymuyor.", so: "Waqti ahaan ma habboona.", fa: "زمانش مناسب نیست.", af: "Dit pas nie goed by my skedule nie." }},
    { de: "Ich bin anderweitig beschäftigt.", t: { ua: "Я зайнятий іншими справами.", tr: "Başka bir işle meşgulüm.", so: "Waxaan ku mashquulsanahay arrimo kale.", fa: "مشغول کار دیگری هستم.", af: "Ek is elders besig." }},
    { de: "Ich kann an diesem Tag nicht.", t: { ua: "У цей день не можу.", tr: "O gün gelemem.", so: "Maalintaas ma imaan karo.", fa: "در آن روز نمی‌توانم.", af: "Ek kan nie daardie dag nie." }},
    { de: "Das ist nicht möglich.", t: { ua: "Це неможливо.", tr: "Bu mümkün değil.", so: "Ma suurtagal.", fa: "این امکان‌پذیر نیست.", af: "Dit is nie moontlik nie." }},
    { de: "Leider habe ich keine Kapazität.", t: { ua: "На жаль, немає можливості.", tr: "Maalesef kapasitem yok.", so: "Nasiib darro ma awoodo.", fa: "متأسفانه ظرفیت ندارم.", af: "Ongelukkig het ek nie kapasiteit nie." }},
    { de: "Das ist terminlich problematisch.", t: { ua: "Час проблемний.", tr: "Zamanlama sorunlu.", so: "Waqti ahaan waa dhibaato.", fa: "زمان مشکلی دارد.", af: "Dit is skeduleer problematies." }},
    { de: "Ich bin an dem Tag nicht verfügbar.", t: { ua: "У цей день недоступний.", tr: "O gün müsait değilim.", so: "Maalintaas ma heli karo.", fa: "در آن روز در دسترس نیستم.", af: "Ek is nie beskikbaar daardie dag nie." }},
    { de: "Ich muss absagen, leider.", t: { ua: "Мушу відмінити, на жаль.", tr: "Maalesef iptal etmem gerekiyor.", so: "Waan ka xumahay, waan joojinayaa.", fa: "متأسفانه باید لغو کنم.", af: "Ek moet ongelukkig afsê." }},
    { de: "Ich habe einen anderen Termin.", t: { ua: "У мене інша зустріч.", tr: "Başka bir randevum var.", so: "Qorshe kale ayaan hayaa.", fa: "قرار دیگری دارم.", af: "Ek het ’n ander afspraak." }},
    { de: "Ich kann nicht zusagen.", t: { ua: "Не можу погодитися.", tr: "Onaylayamam.", so: "Ma xaqiijin karo.", fa: "نمی‌توانم موافقت کنم.", af: "Ek kan nie bevestig nie." }}
  ],
  con: [
    { de: "Wie wäre es etwas später?", t: { ua: "Трохи пізніше?", tr: "Biraz sonra?", so: "Hadhow?", fa: "کمی دیرتر؟", af: "’n Bietjie later?" }},
    { de: "Können wir das verschieben?", t: { ua: "Можемо перенести?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Kan ons dit skuif?" }},
    { de: "Vielleicht an einem anderen Ort?", t: { ua: "В іншому місці?", tr: "Başka yerde?", so: "Meel kale?", fa: "جای دیگر؟", af: "Op ’n ander plek?" }},
    { de: "Lass uns einen anderen Tag nehmen.", t: { ua: "Інший день.", tr: "Başka gün.", so: "Maalin kale.", fa: "روز دیگر.", af: "’n Ander dag." }},
    { de: "Geht es dir morgen?", t: { ua: "Завтра зручно?", tr: "Yarın uygun mu?", so: "Berri ma u fiican?", fa: "فردا مناسب است؟", af: "Werk dit vir jou môre?" }},
    { de: "Wollen wir es verschieben?", t: { ua: "Переносимо?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Wil ons dit skuif?" }},
    { de: "Könnten wir später anfangen?", t: { ua: "Можемо пізніше почати?", tr: "Daha sonra başlayabilir miyiz?", so: "Ma dib u bilaabi karnaa?", fa: "می‌توانیم دیرتر شروع کنیم؟", af: "Kan ons later begin?" }},
    { de: "Passt es dir am Nachmittag?", t: { ua: "Вдень зручно?", tr: "Öğleden sonra uygun mu?", so: "Galab ma u fiican?", fa: "بعد از ظهر مناسب است؟", af: "Pas dit vir jou in die middag?" }},
    { de: "Sollen wir den Ort ändern?", t: { ua: "Змінити місце?", tr: "Yeri değiştirelim mi?", so: "Ma bedeliyaa goobta?", fa: "مکان را تغییر دهیم؟", af: "Moet ons die plek verander?" }},
    { de: "Wollen wir einen anderen Tag nehmen?", t: { ua: "Інший день вибрати?", tr: "Başka gün mü alalım?", so: "Maalin kale ma qaadnaa?", fa: "روز دیگری انتخاب کنیم؟", af: "Wil ons ’n ander dag neem?" }},
    { de: "Können wir es später machen?", t: { ua: "Можемо пізніше зробити?", tr: "Daha sonra yapabilir miyiz?", so: "Ma dib u sameyn karnaa?", fa: "می‌توانیم بعداً انجام دهیم؟", af: "Kan ons dit later doen?" }},
    { de: "Wie wäre es am Abend?", t: { ua: "Ввечері як?", tr: "Akşam nasıl?", so: "Fiidkii sidee?", fa: "شب چطور؟", af: "Hoe gaan dit saans?" }},
    { de: "Passt dir der Nachmittag?", t: { ua: "День підходить?", tr: "Öğleden sonra uygun mu?", so: "Galab ma ku habboon?", fa: "بعد از ظهر مناسب است؟", af: "Pas dit vir jou in die middag?" }},
    { de: "Sollen wir es verschieben?", t: { ua: "Перенести?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Moet ons dit skuif?" }},
    { de: "Können wir einen anderen Tag wählen?", t: { ua: "Інший день вибрати?", tr: "Başka gün seçebilir miyiz?", so: "Maalin kale dooran karnaa?", fa: "روز دیگری انتخاب کنیم؟", af: "Kan ons ’n ander dag kies?" }},
    { de: "Ist später für dich möglich?", t: { ua: "Пізніше можливо для тебе?", tr: "Daha sonra senin için mümkün mü?", so: "Maka dambe ma kuu shaqeyn karaa?", fa: "بعداً برایت ممکن است؟", af: "Is later moontlik vir jou?" }},
    { de: "Sollen wir den Termin verschieben?", t: { ua: "Перенести зустріч?", tr: "Randevuyu erteleyelim mi?", so: "Ma dib u dhigno ballanta?", fa: "جلسه را عقب بیندازیم؟", af: "Moet ons die afspraak skuif?" }},
    { de: "Passt es dir später?", t: { ua: "Пізніше зручно?", tr: "Daha sonra uygun mu?", so: "Maka dambe ma u fiican?", fa: "بعداً مناسب است؟", af: "Pas dit vir jou later?" }},
    { de: "Können wir einen anderen Ort nehmen?", t: { ua: "Взяти інше місце?", tr: "Başka bir yer alabilir miyiz?", so: "Ma meel kale qaadnaa?", fa: "مکان دیگری انتخاب کنیم؟", af: "Kan ons ’n ander plek neem?" }},
    { de: "Wollen wir die Uhrzeit ändern?", t: { ua: "Змінити час?", tr: "Saatini değiştirelim mi?", so: "Ma bedelnaa waqtiga?", fa: "ساعت را تغییر دهیم؟", af: "Wil ons die tyd verander?" }},
    { de: "Vielleicht später?", t: { ua: "Можливо пізніше?", tr: "Belki sonra?", so: "Malaha dambe?", fa: "شاید بعداً؟", af: "Miskien later?" }},
    { de: "Können wir die Zeit ändern?", t: { ua: "Можемо змінити час?", tr: "Zamanı değiştirebilir miyiz?", so: "Ma bedelnaa waqtiga?", fa: "می‌توانیم زمان را تغییر دهیم؟", af: "Kan ons die tyd verander?" }},
    { de: "Wie wäre es morgen?", t: { ua: "Завтра як?", tr: "Yarın nasıl?", so: "Berri sidee?", fa: "فردا چطور؟", af: "Hoe gaan dit môre?" }},
    { de: "Können wir später sprechen?", t: { ua: "Можемо пізніше поговорити?", tr: "Daha sonra konuşabilir miyiz?", so: "Ma dib u hadli karnaa?", fa: "می‌توانیم بعداً صحبت کنیم؟", af: "Kan ons later praat?" }},
    { de: "Passt dir ein anderer Tag?", t: { ua: "Інший день підходить?", tr: "Başka gün uygun mu?", so: "Maalin kale ma ku habboon?", fa: "روز دیگری مناسب است؟", af: "Pas dit vir jou op ’n ander dag?" }},
    { de: "Wollen wir einen späteren Termin?", t: { ua: "Пізніша зустріч?", tr: "Daha sonraki bir randevu mu?", so: "Ballan dambe ma rabnaa?", fa: "جلسه دیرتر؟", af: "Wil ons ’n later afspraak hê?" }},
    { de: "Geht es dir morgen Nachmittag?", t: { ua: "Завтра вдень зручно?", tr: "Yarın öğleden sonra uygun mu?", so: "Berri galab ma u fiican?", fa: "بعد از ظهر فردا مناسب است؟", af: "Werk dit vir jou môre middag?" }},
    { de: "Können wir es auf morgen verschieben?", t: { ua: "Перенести на завтра?", tr: "Yarına erteleyebilir miyiz?", so: "Ma berri u dhigno?", fa: "می‌توانیم به فردا منتقل کنیم؟", af: "Kan ons dit na môre skuif?" }},
    { de: "Vielleicht an einem anderen Tag?", t: { ua: "Можливо інший день?", tr: "Belki başka bir gün?", so: "Malaha maalin kale?", fa: "شاید روز دیگری؟", af: "Miskien op ’n ander dag?" }},
    { de: "Wie wäre es später am Tag?", t: { ua: "Пізніше протягом дня?", tr: "Günün ilerleyen saatleri nasıl?", so: "Maalin dambe?", fa: "بعداً در طول روز؟", af: "Hoe gaan dit later daardie dag?" }},
    { de: "Passt es dir morgen?", t: { ua: "Завтра підходить?", tr: "Yarın uygun mu?", so: "Berri ma ku habboon?", fa: "فردا مناسب است؟", af: "Pas dit vir jou môre?" }},
    { de: "Sollen wir den Termin verschieben?", t: { ua: "Перенести зустріч?", tr: "Randevuyu erteleyelim mi?", so: "Ma dib u dhigno ballanta?", fa: "جلسه را عقب بیندازیم؟", af: "Moet ons die afspraak skuif?" }},
    { de: "Können wir später anfangen?", t: { ua: "Можемо пізніше почати?", tr: "Daha sonra başlayabilir miyiz?", so: "Ma dib u bilaabi karnaa?", fa: "می‌توانیم دیرتر شروع کنیم؟", af: "Kan ons later begin?" }},
    { de: "Vielleicht morgen?", t: { ua: "Можливо завтра?", tr: "Belki yarın?", so: "Malaha berri?", fa: "شاید فردا؟", af: "Miskien môre?" }},
    { de: "Wie sieht es morgen aus?", t: { ua: "Завтра як справи?", tr: "Yarın nasıl görünüyor?", so: "Berri sidee tahay?", fa: "فردا چطور است؟", af: "Hoe lyk dit môre?" }},
    { de: "Sollen wir die Uhrzeit ändern?", t: { ua: "Змінити час?", tr: "Saatini değiştirelim mi?", so: "Ma bedelnaa waqtiga?", fa: "ساعت را تغییر دهیم؟", af: "Wil ons die tyd verander?" }},
    { de: "Geht es dir später?", t: { ua: "Пізніше підходить?", tr: "Daha sonra uygun mu?", so: "Maka dambe ma kuu fiican?", fa: "بعداً مناسب است؟", af: "Pas dit vir jou later?" }},
    { de: "Können wir es verschieben?", t: { ua: "Можемо перенести?", tr: "Erteleyebilir miyiz?", so: "Ma dib u dhigno?", fa: "می‌توانیم منتقل کنیم؟", af: "Kan ons dit skuif?" }},
    { de: "Wie wäre es nächste Woche?", t: { ua: "Наступного тижня як?", tr: "Gelecek hafta nasıl?", so: "Toddobaadka dambe sidee?", fa: "هفته آینده چطور؟", af: "Hoe gaan dit volgende week?" }},
    { de: "Passt dir später am Tag?", t: { ua: "Пізніше протягом дня підходить?", tr: "Günün ilerleyen saatleri uygun mu?", so: "Maalin dambe ma ku habboon?", fa: "بعداً در طول روز مناسب است؟", af: "Pas dit vir jou later daardie dag?" }},
    { de: "Sollen wir einen späteren Zeitpunkt nehmen?", t: { ua: "Взяти пізніший час?", tr: "Daha sonraki bir zaman mı alalım?", so: "Waqti dambe ma qaadnaa?", fa: "زمان دیرتر انتخاب کنیم؟", af: "Moet ons ’n later tyd neem?" }},
    { de: "Können wir auf später verschieben?", t: { ua: "Перенести на пізніше?", tr: "Daha sonra erteleyebilir miyiz?", so: "Ma dib u dhigno?", fa: "می‌توانیم به بعد منتقل کنیم؟", af: "Kan ons na later skuif?" }},
    { de: "Vielleicht später am Tag?", t: { ua: "Можливо пізніше протягом дня?", tr: "Günün ilerleyen saatlerinde belki?", so: "Malaha maalin dambe?", fa: "شاید بعداً در طول روز؟", af: "Miskien later daardie dag?" }}
  ],
  add: [
    { de: "Grundsätzlich", t: { ua: "В принципі", tr: "Genel olarak", so: "Asal ahaan", fa: "اصولا", af: "In beginsel" }},
    { de: "Vielleicht", t: { ua: "Можливо", tr: "Belki", so: "Malaha", fa: "شاید", af: "Miskien" }},
    { de: "Ehrlich gesagt", t: { ua: "Чесно кажучи", tr: "Açıkçası", so: "Si daacad ah", fa: "صادقانه", af: "Eerlikwaar" }},
    { de: "Im Moment", t: { ua: "Зараз", tr: "Şu anda", so: "Hadda", fa: "در حال حاضر", af: "Op die oomblik" }},
    { de: "Normalerweise", t: { ua: "Зазвичай", tr: "Normalde", so: "Caadi ahaan", fa: "معمولاً", af: "Normaalweg" }},
    { de: "Tatsächlich", t: { ua: "Насправді", tr: "Aslında", so: "Dhab ahaantii", fa: "در واقع", af: "Feitlik" }},
    { de: "Außerdem", t: { ua: "До того ж", tr: "Ayrıca", so: "Sidoo kale", fa: "علاوه بر این", af: "Boonop" }},
    { de: "Übrigens", t: { ua: "Між іншим", tr: "Bu arada", so: "By the way", fa: "راستی", af: "Togens" }},
    { de: "Eigentlich", t: { ua: "Власне", tr: "Aslında", so: "Dhab ahaan", fa: "در حقیقت", af: "Egter" }},
    { de: "Insbesondere", t: { ua: "Особливо", tr: "Özellikle", so: "Gaar ahaan", fa: "به ویژه", af: "Veral" }},
    { de: "Generell", t: { ua: "Загалом", tr: "Genel olarak", so: "Guud ahaan", fa: "به طور کلی", af: "Oor die algemeen" }},
    { de: "In der Regel", t: { ua: "Як правило", tr: "Genellikle", so: "Sida caadiga ah", fa: "معمولاً", af: "Gewoonlik" }},
    { de: "Meistens", t: { ua: "Переважно", tr: "Çoğunlukla", so: "Inta badan", fa: "اغلب", af: "Meestal" }},
    { de: "Zudem", t: { ua: "Крім того", tr: "Buna ek olarak", so: "Intaa waxaa dheer", fa: "علاوه بر این", af: "Boonop" }},
    { de: "Abgesehen davon", t: { ua: "Окрім цього", tr: "Bundan ayrı olarak", so: "Ka sokow tan", fa: "به جز این", af: "Afgesien hiervan" }},
    { de: "Demnach", t: { ua: "Отже", tr: "Buna göre", so: "Sidaas darteed", fa: "بنابراین", af: "Dus" }},
    { de: "Ferner", t: { ua: "Також", tr: "Ayrıca", so: "Sidoo kale", fa: "همچنین", af: "Verder" }},
    { de: "Daher", t: { ua: "Тому", tr: "Bundan dolayı", so: "Sidaas darteed", fa: "بنابراین", af: "Daarom" }},
    { de: "Somit", t: { ua: "Таким чином", tr: "Böylece", so: "Sidaas darteed", fa: "بنابراین", af: "Sodoende" }},
    { de: "Zwar", t: { ua: "Хоча", tr: "Gerçi", so: "Inkastoo", fa: "گرچه", af: "Weliswaar" }},
    { de: "Jedoch", t: { ua: "Проте", tr: "Ancak", so: "Si kastaba ha ahaatee", fa: "با این حال", af: "Echter" }},
    { de: "Allerdings", t: { ua: "Проте", tr: "Ancak", so: "Si kastaba ha ahaatee", fa: "البته", af: "Inderdaad" }},
    { de: "Natürlich", t: { ua: "Звичайно", tr: "Tabii ki", so: "Dabcan", fa: "البته", af: "Natuurlik" }},
    { de: "Sicherlich", t: { ua: "Безсумнівно", tr: "Kesinlikle", so: "Hubanti", fa: "مطمئناً", af: "Sekerlik" }},
    { de: "Wahrscheinlich", t: { ua: "Ймовірно", tr: "Muhtemelen", so: "Malaha", fa: "احتمالاً", af: "Waarskynlik" }},
    { de: "Eventuell", t: { ua: "Можливо", tr: "Olası", so: "Malaha", fa: "شاید", af: "Eventueel" }},
    { de: "Grundlegend", t: { ua: "Основоположний", tr: "Temel", so: "Asaasiga ah", fa: "اساسی", af: "Fundamenteel" }},
    { de: "Zusätzlich", t: { ua: "Додатково", tr: "Ek olarak", so: "Dheeraad ah", fa: "علاوه بر این", af: "Bykomend" }},
    { de: "Darüber hinaus", t: { ua: "Крім того", tr: "Bunun ötesinde", so: "Ka sokow tan", fa: "علاوه بر این", af: "Daarby" }},
    { de: "Vermutlich", t: { ua: "Мабуть", tr: "Muhtemelen", so: "Malaha", fa: "احتمالاً", af: "Waarskynlik" }},
    { de: "Zugleich", t: { ua: "Водночас", tr: "Aynı zamanda", so: "Isla markaas", fa: "همزمان", af: "Tegelyk" }},
    { de: "Sozusagen", t: { ua: "Так би мовити", tr: "Tabiri caizse", so: "Sida la dhihi karo", fa: "به اصطلاح", af: "Sowel te sê" }},
    { de: "Inzwischen", t: { ua: "Тим часом", tr: "Bu sırada", so: "Dhexda", fa: "در این میان", af: "Intussen" }},
    { de: "Ebenfalls", t: { ua: "Також", tr: "Ayrıca", so: "Sidoo kale", fa: "نیز", af: "Ook" }},
    { de: "Gleichzeitig", t: { ua: "Одночасно", tr: "Aynı anda", so: "Isla markaas", fa: "به طور همزمان", af: "Tegelyk" }},
    { de: "Zukünftig", t: { ua: "У майбутньому", tr: "Gelecekte", so: "Mustaqbalka", fa: "در آینده", af: "Toekomstig" }},
    { de: "Letztendlich", t: { ua: "В кінцевому рахунку", tr: "Sonuçta", so: "Ugu dambeyntii", fa: "در نهایت", af: "Uiteindelik" }},
    { de: "Im Allgemeinen", t: { ua: "Загалом", tr: "Genel olarak", so: "Guud ahaan", fa: "به طور کلی", af: "Oor die algemeen" }},
    { de: "Daher", t: { ua: "Отже", tr: "Bundan dolayı", so: "Sidaas darteed", fa: "بنابراین", af: "Daarom" }},
    { de: "Demzufolge", t: { ua: "Відповідно", tr: "Buna göre", so: "Sidaas darteed", fa: "بنابراین", af: "Gevolglik" }},
    { de: "Sowohl ... als auch", t: { ua: "Як ... так і ...", tr: "Hem ... hem de ...", so: "Labada ... iyo ...", fa: "هم ... و هم ...", af: "Sowel ... as ... asook" }},
    { de: "Nicht nur ... sondern auch", t: { ua: "Не тільки ... але й ...", tr: "Sadece ... değil, aynı zamanda ...", so: "Kaliya ... ma aha, laakiin sidoo kale ...", fa: "نه تنها ... بلکه ... نیز", af: "Nie net ... maar ook ..." }},
    { de: "Folglich", t: { ua: "Отже", tr: "Sonuç olarak", so: "Sidaas darteed", fa: "بنابراین", af: "Gevolglik" }},
    { de: "Infolgedessen", t: { ua: "Внаслідок цього", tr: "Bunun sonucunda", so: "Natiijada ahaan", fa: "در نتیجه", af: "Gevolglik" }},
    { de: "Damit", t: { ua: "Таким чином", tr: "Böylece", so: "Sidaas darteed", fa: "بدین ترتیب", af: "Sodat" }},
    { de: "Obendrein", t: { ua: "До того ж", tr: "Üstelik", so: "Sidoo kale", fa: "علاوه بر این", af: "Boonop" }},
    { de: "Zuletzt", t: { ua: "Нарешті", tr: "Son olarak", so: "Ugu dambeyntii", fa: "در نهایت", af: "Laastens" }},
    { de: "Schließlich", t: { ua: "Зрештою", tr: "Nihayet", so: "Ugu dambeyntii", fa: "در نهایت", af: "Uiteindelik" }}
  ],
  ask: [
    { de: "Wann passt es dir?", t: { ua: "Коли зручно?", tr: "Ne zaman uygun?", so: "Goorma?", fa: "کی مناسب است؟", af: "Wanneer pas dit?" }},
    { de: "Wo treffen wir uns?", t: { ua: "Де зустрічаємось?", tr: "Nerede?", so: "Xaggee?", fa: "کجا؟", af: "Waar ontmoet ons?" }},
    { de: "Wie lange soll es gehen?", t: { ua: "Як довго?", tr: "Ne kadar?", so: "Intee?", fa: "چقدر؟", af: "Hoe lank?" }},
    { de: "Wer bringt was mit?", t: { ua: "Хто що приносить?", tr: "Kim ne getiriyor?", so: "Yaa maxaa keenaya?", fa: "کی چی می‌آورد؟", af: "Wie bring wat?" }},
    { de: "Mit wem treffen wir uns?", t: { ua: "З ким зустрічаємось?", tr: "Kimle buluşuyoruz?", so: "Kuma la kulmaynaa?", fa: "با کی ملاقات داریم؟", af: "Met wie ontmoet ons?" }},
    { de: "Zu welcher Uhrzeit?", t: { ua: "О котрій годині?", tr: "Saat kaçta?", so: "Waqtigee?", fa: "در چه ساعتی؟", af: "Op watter tyd?" }},
    { de: "An welchem Ort?", t: { ua: "В якому місці?", tr: "Hangi yerde?", so: "Xagee?", fa: "در کجا؟", af: "Op watter plek?" }},
    { de: "Wie viele Personen kommen?", t: { ua: "Скільки людей прийде?", tr: "Kaç kişi gelecek?", so: "Imisa qof ayaa imanaya?", fa: "چند نفر می‌آیند؟", af: "Hoeveel mense kom?" }},
    { de: "Was sollen wir mitbringen?", t: { ua: "Що взяти з собою?", tr: "Ne getirmeliyiz?", so: "Maxaa la keenaa?", fa: "چه چیزی بیاوریم؟", af: "Wat moet ons saambring?" }},
    { de: "Soll ich etwas vorbereiten?", t: { ua: "Мені щось підготувати?", tr: "Bir şey hazırlayayım mı?", so: "Ma diyaariyaa wax?", fa: "چیزی آماده کنم؟", af: "Moet ek iets voorberei?" }},
    { de: "Möchtest du etwas essen?", t: { ua: "Хочеш щось поїсти?", tr: "Bir şey yemek ister misin?", so: "Ma rabtaa wax cunno?", fa: "می‌خوای چیزی بخوری؟", af: "Wil jy iets eet?" }},
    { de: "Brauchen wir Getränke?", t: { ua: "Потрібні напої?", tr: "İçecek lazım mı?", so: "Ma cabitaan baan u baahan nahay?", fa: "نوشیدنی لازم است؟", af: "Het ons drank nodig?" }},
    { de: "Können wir das ändern?", t: { ua: "Можемо це змінити?", tr: "Bunu değiştirebilir miyiz?", so: "Ma beddeli karnaa?", fa: "می‌توانیم تغییر دهیم؟", af: "Kan ons dit verander?" }},
    { de: "Ist das in Ordnung?", t: { ua: "Це нормально?", tr: "Bu uygun mu?", so: "Tani waa hagaag?", fa: "این درست است؟", af: "Is dit reg?" }},
    { de: "Wer übernimmt was?", t: { ua: "Хто що робить?", tr: "Kim ne yapacak?", so: "Yaa maxaa qabanaya?", fa: "کی چه کاری انجام می‌دهد؟", af: "Wie neem wat op?" }},
    { de: "Gibt es ein bestimmtes Datum?", t: { ua: "Є конкретна дата?", tr: "Belirli bir tarih var mı?", so: "Ma jiro taariikh gaar ah?", fa: "تاریخ مشخصی هست؟", af: "Is daar ’n spesifieke datum?" }},
    { de: "Wie sieht der Plan aus?", t: { ua: "Який план?", tr: "Plan nasıl görünüyor?", so: "Maxay qorshuhu u egyahay?", fa: "برنامه چطور است؟", af: "Hoe lyk die plan?" }},
    { de: "Soll es drinnen oder draußen sein?", t: { ua: "Всередині чи на вулиці?", tr: "İçeride mi dışarıda mı?", so: "Ma gudaha mise bannaanka?", fa: "داخل یا بیرون باشد؟", af: "Moet dit binne of buite wees?" }},
    { de: "Welche Kleidung ist passend?", t: { ua: "Який одяг підходить?", tr: "Hangi kıyafet uygun?", so: "Nooca dharka ayaa ku habboon?", fa: "چه لباسی مناسب است؟", af: "Watter klere is gepas?" }},
    { de: "Brauchen wir Tische und Stühle?", t: { ua: "Потрібні столи та стільці?", tr: "Masa ve sandalye lazım mı?", so: "Miisaska iyo kuraasta ma loo baahan yahay?", fa: "به میز و صندلی نیاز داریم؟", af: "Het ons tafels en stoele nodig?" }},
    { de: "Kann jeder kommen?", t: { ua: "Може кожен прийти?", tr: "Herkes gelebilir mi?", so: "Qof walbaa imaan karaa?", fa: "همه می‌توانند بیایند؟", af: "Kan almal kom?" }},
    { de: "Ist es ein privates Treffen?", t: { ua: "Це приватна зустріч?", tr: "Bu özel bir buluşma mı?", so: "Ma kulanka gaarka ah?", fa: "این ملاقات خصوصی است؟", af: "Is dit ’n private ontmoeting?" }},
    { de: "Darf man Gäste mitbringen?", t: { ua: "Можна привести гостей?", tr: "Misafir getirebilir miyiz?", so: "Ma keeni kartaa marti?", fa: "می‌توان مهمان آورد؟", af: "Mag mens gaste saambring?" }},
    { de: "Wie viele Stunden dauert es?", t: { ua: "Скільки годин триватиме?", tr: "Kaç saat sürecek?", so: "Imisa saacadood ayey socon doontaa?", fa: "چند ساعت طول می‌کشد؟", af: "Hoeveel ure duur dit?" }},
    { de: "Welche Getränke gibt es?", t: { ua: "Які напої будуть?", tr: "Hangi içecekler var?", so: "Maxaa cabitaan ah?", fa: "چه نوشیدنی‌هایی هست؟", af: "Watter drankies is daar?" }},
    { de: "Kann ich etwas mitbringen?", t: { ua: "Можу щось принести?", tr: "Bir şey getirebilir miyim?", so: "Ma keeni karaa wax?", fa: "می‌توانم چیزی بیاورم؟", af: "Kan ek iets saambring?" }},
    { de: "Brauchen wir Musik?", t: { ua: "Потрібна музика?", tr: "Müziğe ihtiyaç var mı?", so: "Ma muusig baa loo baahan yahay?", fa: "موسیقی لازم است؟", af: "Het ons musiek nodig?" }},
    { de: "Wie ist das Wetter geplant?", t: { ua: "Яка погода очікується?", tr: "Hava nasıl olacak?", so: "Cimiladu sidee tahay?", fa: "هوا چگونه خواهد بود؟", af: "Hoe lyk die weer?" }},
    { de: "Wer bringt Essen mit?", t: { ua: "Хто принесе їжу?", tr: "Kim yemek getirecek?", so: "Yaa cunto keeni doona?", fa: "چه کسی غذا می‌آورد؟", af: "Wie bring kos saam?" }},
    { de: "Gibt es ein Programm?", t: { ua: "Є програма?", tr: "Bir program var mı?", so: "Ma jiro barnaamij?", fa: "برنامه‌ای هست؟", af: "Is daar ’n program?" }},
    { de: "Müssen wir etwas vorbereiten?", t: { ua: "Потрібно щось підготувати?", tr: "Bir şey hazırlamalı mıyız?", so: "Ma u baahan nahay inaan diyaarinno wax?", fa: "چیزی آماده کنیم؟", af: "Moet ons iets voorberei?" }},
    { de: "Soll ich früh kommen?", t: { ua: "Мені раніше прийти?", tr: "Erken gelmeli miyim?", so: "Ma hore u imaadaa?", fa: "زودتر بیایم؟", af: "Moet ek vroeg kom?" }},
    { de: "Darf ich jemanden einladen?", t: { ua: "Можу когось запросити?", tr: "Birini davet edebilir miyim?", so: "Ma casuumi karaa qof?", fa: "می‌توانم کسی را دعوت کنم؟", af: "Mag ek iemand nooi?" }},
    { de: "Wie viele kommen insgesamt?", t: { ua: "Скільки всього прийде?", tr: "Toplam kaç kişi gelecek?", so: "Imisa qof ayaa guud ahaan imanaya?", fa: "چند نفر کلآ می‌آیند؟", af: "Hoeveel kom in totaal?" }},
    { de: "Können wir vorher sprechen?", t: { ua: "Можемо поговорити заздалегідь?", tr: "Önceden konuşabilir miyiz?", so: "Ma hore u hadli karnaa?", fa: "می‌توانیم قبلاً صحبت کنیم؟", af: "Kan ons vooraf praat?" }},
    { de: "Brauchen wir Snacks?", t: { ua: "Потрібні снеки?", tr: "Atıştırmalık lazım mı?", so: "Ma u baahan nahay cunto fudud?", fa: "به خوراکی نیاز داریم؟", af: "Het ons happies nodig?" }},
    { de: "Soll es formell sein?", t: { ua: "Це має бути офіційно?", tr: "Resmi mi olmalı?", so: "Ma aha rasmi?", fa: "رسمی باشد؟", af: "Moet dit formeel wees?" }},
    { de: "Möchtest du Hilfe?", t: { ua: "Хочеш допомогу?", tr: "Yardım ister misin?", so: "Ma rabtaa caawimo?", fa: "کمک می‌خوای؟", af: "Wil jy hulp hê?" }},
    { de: "Wie sollen wir uns kleiden?", t: { ua: "Як одягнутись?", tr: "Nasıl giyinelim?", so: "Sidee u labisnaa?", fa: "چطور لباس بپوشیم؟", af: "Hoe moet ons aantrek?" }},
    { de: "Soll es drinnen bleiben?", t: { ua: "Залишимо всередині?", tr: "İçeride mi kalsın?", so: "Ma gudaha ha ahaado?", fa: "داخل بماند؟", af: "Moet dit binne bly?" }},
    { de: "Wie viele Kinder kommen?", t: { ua: "Скільки дітей прийде?", tr: "Kaç çocuk gelecek?", so: "Imisa caruur ayaa imanaya?", fa: "چند کودک می‌آیند؟", af: "Hoeveel kinders kom?" }},
    { de: "Brauchen wir Stühle?", t: { ua: "Потрібні стільці?", tr: "Sandalye lazım mı?", so: "Ma u baahan nahay kuraas?", fa: "به صندلی نیاز داریم؟", af: "Het ons stoele nodig?" }},
    { de: "Kann jeder teilnehmen?", t: { ua: "Може кожен брати участь?", tr: "Herkes katılabilir mi?", so: "Qof walbaa ka qayb qaadan karaa?", fa: "همه می‌توانند شرکت کنند؟", af: "Kan almal deelneem?" }},
    { de: "Gibt es besondere Regeln?", t: { ua: "Є особливі правила?", tr: "Özel kurallar var mı?", so: "Ma jiraan xeerar gaar ah?", fa: "قوانین خاصی وجود دارد؟", af: "Is daar spesiale reëls?" }},
    { de: "Wer übernimmt die Organisation?", t: { ua: "Хто організовує?", tr: "Organizasyonu kim üstlenecek?", so: "Yaa qaban doona?", fa: "چه کسی سازماندهی می‌کند؟", af: "Wie neem die organisasie op?" }},
    { de: "Müssen wir etwas kaufen?", t: { ua: "Потрібно щось купити?", tr: "Bir şey almamız gerekiyor mu?", so: "Ma u baahan nahay inaan wax iibsanno?", fa: "چیزی باید بخریم؟", af: "Moet ons iets koop?" }}
  ]
};