const DATA = {
  pro: [
    { de: "Sollen wir uns am See treffen?", t:{ ua:"Зустрінемось біля озера?", tr:"Göl kenarında buluşalım mı?", so:"Harada ku kulannaa?", fa:"کنار دریاچه همدیگر را ببینیم؟", af:"Sal ons by die meer ontmoet?" }},
    { de: "Wie wäre es mit einem Picknick am Wochenende?", t:{ ua:"Як щодо пікніка на вихідних?", tr:"Hafta sonu piknik yapalım mı?", so:"Dhammaadka usbuuca picnic?", fa:"آخر هفته پیک‌نیک چطور؟", af:"’n Piekniek oor die naweek?" }},
    { de: "Lass uns etwas Einfaches planen.", t:{ ua:"Давай щось просте.", tr:"Basit bir şey planlayalım.", so:"Aan wax fudud qorshayno.", fa:"بیایید ساده برنامه‌ریزی کنیم.", af:"Kom ons hou dit eenvoudig." }},
    { de: "Ich schlage vor, wir treffen uns nach der Arbeit.", t:{ ua:"Пропоную після роботи.", tr:"İşten sonra buluşalım.", so:"Shaqada kadib aan kulanno.", fa:"بعد از کار ملاقات کنیم.", af:"Kom ons ontmoet ná werk." }},
    { de: "Wir könnten gemeinsam kochen.", t:{ ua:"Можемо разом готувати.", tr:"Birlikte yemek yapabiliriz.", so:"Wada karino.", fa:"با هم آشپزی کنیم.", af:"Ons kan saam kook." }},
    { de: "Vielleicht machen wir es bei mir.", t:{ ua:"Можливо, у мене.", tr:"Belki bende.", so:"Malaha gurigayga.", fa:"شاید خانه من.", af:"Miskien by my." }},
    { de: "Ich bringe Getränke mit.", t:{ ua:"Я принесу напої.", tr:"İçecekleri ben getiririm.", so:"Cabitaan waan keenaa.", fa:"من نوشیدنی می‌آورم.", af:"Ek bring drankies." }},
    { de: "Wollen wir uns am Treffpunkt beim Bahnhof sehen?", t:{ ua:"Зустрінемось біля Treffpunkt на вокзалі?", tr:"İstasyondaki Treffpunkt’te buluşalım mı?", so:"Ma ku kulannaa Treffpunkt-ka?", fa:"در Treffpunkt ایستگاه همدیگر را ببینیم؟", af:"Ontmoet ons by die Treffpunkt by die stasie?" }},
    { de: "Vielleicht nach der Arbeit ein Bier?", t:{ ua:"Може пиво після роботи?", tr:"İşten sonra bir bira?", so:"Shaqada kadib biir?", fa:"بعد از کار یک آبجو؟", af:"’n Bier ná werk?" }},
    { de: "Lass uns das Wetter ausnutzen.", t:{ ua:"Скористаймось гарною погодою.", tr:"Havayı değerlendirelim.", so:"Cimilada ka faa’iidaysanno.", fa:"از هوا استفاده کنیم.", af:"Kom ons benut die weer." }},
    { de: "Wir könnten grillieren.", t:{ ua:"Можемо посмажити на грилі.", tr:"Mangal yapabiliriz.", so:"Waan dubi karnaa.", fa:"می‌توانیم گریل کنیم.", af:"Ons kan braai." }},
    { de: "Hast du Lust auf einen Spaziergang?", t:{ ua:"Хочеш прогулятись?", tr:"Yürüyüşe var mısın?", so:"Socod ma rabtaa?", fa:"حوصله پیاده‌روی داری؟", af:"Lus vir ’n stap?" }},
    { de: "Sollen wir zusammen ÖV fahren?", t:{ ua:"Поїдемо разом ÖV?", tr:"Toplu taşımayla gidelim mi?", so:"Gaadiidka dadweynaha wada raacnaa?", fa:"با حمل‌ونقل عمومی برویم؟", af:"Gebruik ons saam openbare vervoer?" }},
    { de: "Vielleicht ein Kaffee in der Stadt?", t:{ ua:"Може кава в місті?", tr:"Şehirde kahve?", so:"Qaxwo magaalada?", fa:"قهوه در شهر؟", af:"’n Koffie in die stad?" }},
    { de: "Wollen wir das spontan entscheiden?", t:{ ua:"Вирішимо спонтанно?", tr:"Spontane karar verelim mi?", so:"Si kedis ah u go’aaminnaa?", fa:"خودجوش تصمیم بگیریم؟", af:"Besluit ons spontaan?" }},
    { de: "Lass uns etwas Kleines machen.", t:{ ua:"Зробімо щось невелике.", tr:"Küçük bir şey yapalım.", so:"Wax yar sameyno.", fa:"کار کوچکی بکنیم.", af:"Kom ons doen iets kleins." }},
    { de: "Wie wäre es heute Abend?", t:{ ua:"Як щодо сьогодні ввечері?", tr:"Bu akşam nasıl?", so:"Caawa sidee?", fa:"امشب چطور؟", af:"Hoe lyk vanaand?" }},
    { de: "Hast du morgen Zeit?", t:{ ua:"Маєш час завтра?", tr:"Yarın vaktin var mı?", so:"Berri waqti ma haysaa?", fa:"فردا وقت داری؟", af:"Het jy môre tyd?" }},
    { de: "Sollen wir etwas zusammen unternehmen?", t:{ ua:"Зробимо щось разом?", tr:"Birlikte bir şey yapalım mı?", so:"Wax wada sameynaa?", fa:"کاری را با هم انجام دهیم؟", af:"Doen ons iets saam?" }},
    { de: "Vielleicht nur kurz.", t:{ ua:"Може ненадовго.", tr:"Kısa bir süre.", so:"Wax yar.", fa:"کوتاه.", af:"Net kortliks." }},
    { de: "Ich hätte eine Idee.", t:{ ua:"У мене є ідея.", tr:"Bir fikrim var.", so:"Fikir ayaan hayaa.", fa:"یک ایده دارم.", af:"Ek het ’n idee." }},
    { de: "Wollen wir es entspannt halten?", t:{ ua:"Зробимо це спокійно?", tr:"Rahat tutalım mı?", so:"Si deggan?", fa:"آرام نگه داریم؟", af:"Hou ons dit rustig?" }},
    { de: "Vielleicht am Fluss entlang.", t:{ ua:"Можливо вздовж річки.", tr:"Nehir boyunca.", so:"Webiga agtiisa.", fa:"کنار رودخانه.", af:"Langs die rivier." }},
    { de: "Vielleicht in den Park gehen?", t:{ ua:"Може підемо в парк?", tr:"Parkta buluşalım mı?", so:"Beerta aan aadno?", fa:"شاید به پارک برویم؟", af:"Miskien na die park?" }},
    { de: "Lass uns eine Runde spazieren.", t:{ ua:"Прогуляємося.", tr:"Bir tur yürüyelim.", so:"Socod sameyno.", fa:"یک دور قدم بزنیم.", af:"Kom ons stap 'n bietjie." }},
    { de: "Wollen wir uns auf einen Drink treffen?", t:{ ua:"Зустрінемось на напій?", tr:"Bir içki için buluşalım mı?", so:"Ma cabitaan kulan?", fa:"برای یک نوشیدنی ملاقات کنیم؟", af:"Ontmoet ons vir ’n drink?" }},
    { de: "Vielleicht bei mir im Garten.", t:{ ua:"Можливо у мене в саду.", tr:"Belki bahçemde.", so:"Malaha beerta gurigayga.", fa:"شاید در باغ من.", af:"Miskien in my tuin." }},
    { de: "Ich hätte Lust auf Spieleabend.", t:{ ua:"Хочу вечір ігор.", tr:"Oyun gecesi isterim.", so:"Waxaan rabaa habeen ciyaaro.", fa:"دوست دارم شب بازی داشته باشیم.", af:"Ek het lus vir ’n speletjiesaand." }},
    { de: "Sollen wir etwas Kochen?", t:{ ua:"Щось приготувати?", tr:"Bir şey pişirelim mi?", so:"Wax cuno karno?", fa:"چیزی بپزیم؟", af:"Kook ons iets?" }},
    { de: "Wie wäre es mit einem Filmabend?", t:{ ua:"Може кіно ввечері?", tr:"Film gecesi nasıl?", so:"Filim habeen?", fa:"شب فیلم چطور؟", af:"’n Fliek-aand?" }},
    { de: "Vielleicht draußen essen?", t:{ ua:"Може поїсти на вулиці?", tr:"Dışarıda yemek?", so:"Bannaanka wax cuno?", fa:"شاید بیرون غذا بخوریم؟", af:"Miskien eet buite?" }},
    { de: "Lass uns etwas Neues ausprobieren.", t:{ ua:"Спробуємо щось нове.", tr:"Yeni bir şey deneyelim.", so:"Wax cusub isku dayno.", fa:"چیزی جدید امتحان کنیم.", af:"Kom ons probeer iets nuuts." }},
    { de: "Sollen wir zusammen Musik hören?", t:{ ua:"Слухати музику разом?", tr:"Birlikte müzik dinleyelim mi?", so:"Ma wada dhageysano muusig?", fa:"با هم موسیقی گوش دهیم؟", af:"Luister ons saam na musiek?" }},
    { de: "Vielleicht eine kleine Wanderung?", t:{ ua:"Можливо невеликий похід?", tr:"Küçük bir yürüyüş?", so:"Socod yar?", fa:"یک پیاده‌روی کوتاه؟", af:"’n Klein stap?" }},
    { de: "Lass uns spontan entscheiden.", t:{ ua:"Вирішимо спонтанно.", tr:"Spontane karar verelim.", so:"Si kedis ah u go’aamino.", fa:"به صورت خودجوش تصمیم بگیریم.", af:"Besluit ons spontaan." }},
    { de: "Wollen wir etwas Sport machen?", t:{ ua:"Зайнятися спортом?", tr:"Spor yapalım mı?", so:"Isboort sameyno?", fa:"ورزش کنیم؟", af:"Doen ons sport?" }},
    { de: "Vielleicht ins Museum gehen?", t:{ ua:"Може в музей?", tr:"Müzeye gidelim mi?", so:"Muzee tagno?", fa:"به موزه برویم؟", af:"Miskien na die museum?" }},
    { de: "Ich hätte Lust auf Eis.", t:{ ua:"Хочу морозиво.", tr:"Dondurma isterim.", so:"Waxaan rabaa baraf macaan.", fa:"دوست دارم بستنی بخورم.", af:"Ek het lus vir roomys." }},
    { de: "Sollen wir zusammen einkaufen?", t:{ ua:"Піти разом за покупками?", tr:"Birlikte alışverişe gidelim mi?", so:"Ma wada wax iibsanno?", fa:"با هم خرید کنیم؟", af:"Gaan ons saam inkopies doen?" }},
    { de: "Vielleicht ein Picknick im Park?", t:{ ua:"Пікнік у парку?", tr:"Parkta piknik?", so:"Picknick beerta?", fa:"پیک‌نیک в парку?", af:"’n Piekniek in die park?" }},
    { de: "Wie wäre es mit einem Abendspaziergang?", t:{ ua:"Вечірня прогулянка?", tr:"Akşam yürüyüşü?", so:"Socod habeen?", fa:"پیاده‌روی شبانه چطور؟", af:"’n Aandstap?" }},
    { de: "Lass uns spontan etwas unternehmen.", t:{ ua:"Зробимо щось спонтанно.", tr:"Spontane bir şey yapalım.", so:"Wax si kedis ah sameyno.", fa:"چیزی خودجوش انجام دهیم.", af:"Kom ons doen iets spontaan." }},
    { de: "Vielleicht einen Ausflug machen?", t:{ ua:"Може зробимо поїздку?", tr:"Bir gezi yapalım mı?", so:"Safar yar sameyno?", fa:"یک سفر کوتاه؟", af:"Miskien ’n uitstappie?" }},
    { de: "Wollen wir zusammen kochen lernen?", t:{ ua:"Навчитися готувати разом?", tr:"Birlikte yemek yapmayı öğrenelim mi?", so:"Ma wada karno baranno?", fa:"با هم آشپزی یاد بگیریم؟", af:"Leer ons saam kook?" }},
    { de: "Ich hätte Lust auf einen Kaffee.", t:{ ua:"Хочу кави.", tr:"Kahve isterim.", so:"Waxaan rabaa qaxwo.", fa:"دوست دارم قهوه بخورم.", af:"Ek het lus vir koffie." }},
    { de: "Vielleicht ein Abendessen planen?", t:{ ua:"Плануємо вечерю?", tr:"Akşam yemeği planlayalım mı?", so:"Habeen cunto qorshayno?", fa:"شام را برنامه‌ریزی کنیم؟", af:"Plan ons ’n aandete?" }},
    { de: "Sollen wir zusammen Sport treiben?", t:{ ua:"Займатися спортом разом?", tr:"Birlikte spor yapalım mı?", so:"Isboort wada sameyno?", fa:"با هم ورزش کنیم؟", af:"Doen ons saam sport?" }},
    { de: "Vielleicht einen Film schauen?", t:{ ua:"Подивимося фільм?", tr:"Film izleyelim mi?", so:"Filim daawanno?", fa:"فیلم ببینیم؟", af:"Kyk ons ’n fliek?" }},
    { de: "Lass uns eine Runde quatschen.", t:{ ua:"Поговоримо трохи.", tr:"Biraz sohbet edelim.", so:"Waan sheekaysannaa.", fa:"کمی گپ بزنیم.", af:"Kom ons gesels 'n bietjie." }},
    { de: "Wollen wir etwas Kreatives machen?", t:{ ua:"Зробимо щось креативне?", tr:"Yaratıcı bir şey yapalım mı?", so:"Wax hal abuur ah sameyno?", fa:"کاری خلاقانه انجام دهیم؟", af:"Doen ons iets kreatief?" }},
    { de: "Vielleicht nur zu zweit?", t:{ ua:"Може тільки вдвох?", tr:"Sadece ikimiz mi?", so:"Kaliya laba?", fa:"فقط دو نفره؟", af:"Miskien net ons twee?" }},
    { de: "Ich hätte Lust auf einen Spaziergang.", t:{ ua:"Хочу прогулянку.", tr:"Yürüyüş yapmak isterim.", so:"Waxaan rabaa socod.", fa:"دوست دارم قدم بزنم.", af:"Ek het lus vir ’n stap." }},
    { de: "Sollen wir etwas Neues probieren?", t:{ ua:"Спробуємо щось нове?", tr:"Yeni bir şey deneyelim mi?", so:"Wax cusub isku dayno?", fa:"چیزی جدید امتحان کنیم؟", af:"Probeer ons iets nuuts?" }},
    { de: "Vielleicht eine kleine Party?", t:{ ua:"Може маленька вечірка?", tr:"Küçük bir parti?", so:"Xaflad yar?", fa:"یک مهمانی کوچک؟", af:"’n Klein partytjie?" }},
    { de: "Lass uns gemeinsam backen.", t:{ ua:"Можемо разом пекти.", tr:"Birlikte fırınlayalım.", so:"Waan wada dubi karnaa.", fa:"با هم بپزیم.", af:"Kom ons saam bak." }},
    { de: "Wollen wir einen Ausflug planen?", t:{ ua:"Сплануємо поїздку?", tr:"Bir gezi planlayalım mı?", so:"Safar qorsheeyo?", fa:"سفر را برنامه‌ریزی کنیم؟", af:"Plan ons ’n uitstappie?" }},
    { de: "Vielleicht nur ein kurzes Treffen?", t:{ ua:"Може коротка зустріч?", tr:"Kısa bir buluşma?", so:"Kulanka gaaban?", fa:"یک ملاقات کوتاه؟", af:"Net ’n kort ontmoeting?" }},
    { de: "Ich hätte Lust auf ein Eis.", t:{ ua:"Хочу морозиво.", tr:"Dondurma isterim.", so:"Waxaan rabaa baraf macaan.", fa:"دوست دارم بستنی.", af:"Ek het lus vir roomys." }},
    { de: "Sollen wir draußen sitzen?", t:{ ua:"Сидіти на вулиці?", tr:"Dışarıda oturalım mı?", so:"Bannaanka fadhiiso?", fa:"در بیرون بنشینیم؟", af:"Sit ons buite?" }},
    { de: "Vielleicht ein kleines Picknick?", t:{ ua:"Може маленький пікнік?", tr:"Küçük bir piknik?", so:"Picknick yar?", fa:"یک پیک‌نیک کوچک؟", af:"’n Klein piekniek?" }},
    { de: "Lass uns spontan etwas essen.", t:{ ua:"З’їмо щось спонтанно.", tr:"Spontane bir şey yiyelim.", so:"Wax si kedis ah wax cuno.", fa:"چیزی خودجوش بخوریم.", af:"Kom ons eet spontaan iets." }},
    { de: "Es gibt nichts mehr vorzuschlagen.", t:{ ua:"Більше нічого запропонувати.", tr:"Önerecek başka bir şey yok.", so:"Wax kale oo la soo jeediyo ma jiro.", fa:"چیز دیگری برای پیشنهاد دادن وجود ندارد.", af:"Daar is niks meer om voor te stel nie." }},
    { de: "Wie klingt das für dich?", t:{ ua:"Як тобі це звучить?", tr:"Sana nasıl geliyor?", so:"Sidee kula tahay?", fa:"به نظرت چطور است؟", af:"Hoe klink dit vir jou?" }},
    { de: "Ich schlage vor, dass wir uns treffen.", t:{ ua:"Я пропоную, щоб ми зустрілися.", tr:"Buluşmamızı öneriyorum.", so:"Waxaan soo jeedinayaa inaan kulanno.", fa:"پیشنهاد می‌کنم که همدیگر را ببینیم.", af:"Ek stel voor dat ons ontmoet." }},
    { de: "Wie wäre es, wenn wir uns treffen?", t:{ ua:"Як щодо того, щоб нам зустрітися?", tr:"Buluşsak nasıl olur?", so:"Sidee bay ahaan lahayd haddii aan kulanno?", fa:"چطور است اگر همدیگر را ببینیم؟", af:"Hoe sal dit wees as ons ontmoet?" }},
    { de: "Könnten wir uns treffen?", t:{ ua:"Чи могли б ми зустрітися?", tr:"Buluşabilir miyiz?", so:"Ma kulmi karnaa?", fa:"می‌توانیم همدیگر را ببینیم؟", af:"Kan ons ontmoet?" }},
    { de: "Hattest du Lust auf ein Treffen?", t:{ ua:"Чи хотів(ла) б ти зустрітися?", tr:"Buluşmak ister misin?", so:"Ma rabtaa inaan kulanno?", fa:"دوست داری همدیگر را ببینیم؟", af:"Het jy lus om te ontmoet?" }},
    { de: "Lass uns uns treffen.", t:{ ua:"Давай зустрінемося.", tr:"Hadi buluşalım.", so:"Aan kulanno.", fa:"بیایید همدیگر را ببینیم.", af:"Kom ons ontmoet." }},
    { de: "Es gibt nichts mehr vorzuschlagen.", t:{ ua:"Більше нічого запропонувати.", tr:"Önerecek başka bir şey yok.", so:"Wax kale oo la soo jeediyo ma jiro.", fa:"چیز دیگری برای پیشنهاد دادن وجود ندارد.", af:"Daar is niks meer om voor te stel nie." }}
  ],
  
  agr: [
    { de: "Klingt gut.", t: { ua: "Звучить добре.", tr: "Kulağa hoş geliyor.", so: "Waa fiican.", fa: "خوب به نظر می‌رسد.", af: "Klink goed." }},
    { de: "Das passt für mich.", t: { ua: "Мені підходить.", tr: "Bana uyar.", so: "Way ii shaqaysaa.", fa: "برای من مناسب است.", af: "Dit werk vir my." }},
    { de: "Gute Idee.", t: { ua: "Хороша ідея.", tr: "İyi fikir.", so: "Fikir fiican.", fa: "ایده خوب.", af: "Goeie idee." }},
    { de: "Einverstanden.", t: { ua: "Згоден.", tr: "Kabul.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek stem saam." }},
    { de: "Ja, gerne.", t: { ua: "Так, залюбки.", tr: "Evet, memnuniyetle.", so: "Haa, dabcan.", fa: "بله.", af: "Ja, graag." }},
    { de: "Perfekt.", t: { ua: "Ідеально.", tr: "Mükemmel.", so: "Wanaagsan.", fa: "عالی.", af: "Perfek." }},
    { de: "Bin dabei.", t: { ua: "Я з вами.", tr: "Varım.", so: "Waan joogaa.", fa: "هستم.", af: "Ek is in." }},
    { de: "Das macht Sinn.", t: { ua: "Має сенс.", tr: "Mantıklı.", so: "Macno leh.", fa: "منطقی است.", af: "Dit maak sin." }},
    { de: "Natürlich.", t: { ua: "Звичайно.", tr: "Tabii ki.", so: "Dabcan.", fa: "البته.", af: "Natuurlik." }},
    { de: "Abgemacht.", t: { ua: "Домовились.", tr: "Anlaşıldı.", so: "Waa la isku raacay.", fa: "موافقیم.", af: "Afgespreek." }},
    { de: "Sehr gut.", t: { ua: "Дуже добре.", tr: "Çok iyi.", so: "Aad u fiican.", fa: "خیلی خوب.", af: "Baie goed." }},
    { de: "Ich stimme zu.", t: { ua: "Я погоджуюсь.", tr: "Katılıyorum.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek stem saam." }},
    { de: "Klar.", t: { ua: "Зрозуміло.", tr: "Tabii.", so: "Haa.", fa: "حتماً.", af: "Duidelik." }},
    { de: "Einfach super.", t: { ua: "Просто супер.", tr: "Harika.", so: "Aad u fiican.", fa: "فوق‌العاده.", af: "Regtig super." }},
    { de: "Top.", t: { ua: "Відмінно.", tr: "Harika.", so: "Sare.", fa: "عالی.", af: "Top." }},
    { de: "Genau.", t: { ua: "Саме так.", tr: "Tam olarak.", so: "Sida saxda ah.", fa: "دقیقا.", af: "Presies." }},
    { de: "Alles klar.", t: { ua: "Все ясно.", tr: "Her şey tamam.", so: "Wax walba waa cad.", fa: "همه چیز روشن است.", af: "Alles duidelik." }},
    { de: "Ich bin einverstanden.", t: { ua: "Я згоден.", tr: "Kabul ediyorum.", so: "Waan oggolahay.", fa: "موافقم.", af: "Ek is saam." }},
    { de: "Passt schon.", t: { ua: "Підходить.", tr: "Uygun.", so: "Waa ku habboon.", fa: "مناسب است.", af: "Dit werk." }},
    { de: "Keine Einwände.", t: { ua: "Без заперечень.", tr: "İtiraz yok.", so: "Dooda ma jirto.", fa: "بدون اعتراض.", af: "Geen besware." }},
    { de: "Alles bestens.", t: { ua: "Все чудово.", tr: "Her şey mükemmel.", so: "Wax walba waa fiican.", fa: "همه چیز عالی.", af: "Alles uitstekend." }},
    { de: "Prima.", t: { ua: "Відмінно.", tr: "Harika.", so: "Wanaagsan.", fa: "عالی.", af: "Prima." }},
    { de: "Super Idee.", t: { ua: "Супер ідея.", tr: "Süper fikir.", so: "Fikir aad u fiican.", fa: "ایده عالی.", af: "Super idee." }},
    { de: "Freut mich.", t: { ua: "Радий.", tr: "Memnun oldum.", so: "Waan ku faraxsanahay.", fa: "خوشحالم.", af: "Ek is bly." }},
    { de: "Natürlich gerne.", t: { ua: "Звичайно.", tr: "Tabii ki.", so: "Dabcan.", fa: "البته.", af: "Natuurlik graag." }},
    { de: "Sehr gerne.", t: { ua: "З великим задоволенням.", tr: "Memnuniyetle.", so: "Si farxad leh.", fa: "با کمال میل.", af: "Baie graag." }},
    { de: "Mit Vergnügen.", t: { ua: "З радістю.", tr: "Ze memnuniyetle.", so: "Farxad ku.", fa: "با خوشحالی.", af: "Met plesier." }},
    { de: "Auf jeden Fall.", t: { ua: "Обов’язково.", tr: "Kesinlikle.", so: "Dabcan.", fa: "حتما.", af: "In elk geval." }},
    { de: "Ich freue mich.", t: { ua: "Радий.", tr: "Sevinçliyim.", so: "Waan ku faraxsanahay.", fa: "خوشحالم.", af: "Ek sien uit daarna." }},
    { de: "Alles in Ordnung.", t: { ua: "Все в порядку.", tr: "Her şey yolunda.", so: "Wax walba waa hagaagsan.", fa: "همه چیز مرتب است.", af: "Alles in orde." }},
    { de: "Passt perfekt.", t: { ua: "Ідеально підходить.", tr: "Mükemmel uyuyor.", so: "Si fiican ayuu u habboon yahay.", fa: "کاملاً مناسب است.", af: "Dit pas perfek." }},
    { de: "Sehr schön.", t: { ua: "Дуже гарно.", tr: "Çok güzel.", so: "Aad u qurux badan.", fa: "خیلی زیبا.", af: "Baie mooi." }},
    { de: "Exzellent.", t: { ua: "Відмінно.", tr: "Mükemmel.", so: "Heer sare.", fa: "عالی.", af: "Uitstekend." }},
    { de: "Absolut.", t: { ua: "Абсолютно.", tr: "Kesinlikle.", so: "Dhab ahaantii.", fa: "کاملاً.", af: "Absoluut." }},
    { de: "Stimmt.", t: { ua: "Правильно.", tr: "Doğru.", so: "Sax.", fa: "درسته.", af: "Stel reg." }},
    { de: "Ich bin dafür.", t: { ua: "Я за.", tr: "Buna katılıyorum.", so: "Waan taageersanahay.", fa: "من موافقم.", af: "Ek is daarvoor." }},
    { de: "Kann ich nur zustimmen.", t: { ua: "Тільки можу погодитись.", tr: "Sadece katılıyorum.", so: "Kaliya waan ku raacsanahay.", fa: "فقط می‌توانم موافقت کنم.", af: "Ek kan net saamstem." }},
    { de: "Das ist richtig.", t: { ua: "Це правильно.", tr: "Bu doğru.", so: "Taas waa sax.", fa: "درسته.", af: "Dit is reg." }},
    { de: "Volle Zustimmung.", t: { ua: "Повна згода.", tr: "Tam onay.", so: "Ogolaansho buuxda.", fa: "کاملاً موافقم.", af: "Volle instemming." }},
    { de: "Absolut richtig.", t: { ua: "Абсолютно правильно.", tr: "Kesinlikle doğru.", so: "Dhab ahaantii sax.", fa: "کاملاً درست.", af: "Absoluut reg." }},
    { de: "Einwandfrei.", t: { ua: "Бездоганно.", tr: "Mükemmel.", so: "Si fiican.", fa: "بی‌نقص.", af: "Onberispelik." }},
    { de: "Richtig so.", t: { ua: "Так правильно.", tr: "Doğru.", so: "Sax sidaas.", fa: "درست است.", af: "Reg so." }},
    { de: "Sehr gut gemacht.", t: { ua: "Дуже добре зроблено.", tr: "Çok iyi yapıldı.", so: "Si fiican loo sameeyey.", fa: "خیلی خوب انجام شد.", af: "Baie goed gedoen." }},
    { de: "Alles bestens erledigt.", t: { ua: "Все відмінно виконано.", tr: "Her şey mükemmel yapıldı.", so: "Wax walba si fiican loo qabtay.", fa: "همه چیز عالی انجام شد.", af: "Alles uitstekend gedoen." }},
    { de: "Ich stimme dir zu.", t:{ ua:"Я з тобою згоден(на).", tr:"Sana katılıyorum.", so:"Waan kugu raacsanahay.", fa:"با تو موافقم.", af:"Ek stem saam met jou." }},
    { de: "Ich bin einverstanden.", t:{ ua:"Я згоден(на).", tr:"Kabul ediyorum.", so:"Waan oggolahay.", fa:"موافقم.", af:"Ek stem in." }},
    { de: "Ich sehe das genau gleich.", t:{ ua:"Я бачу це так само.", tr:"Ben de aynı şekilde görüyorum.", so:"Aniguna sidaas oo kale ayaan u arkaa.", fa:"من هم دقیقاً همین‌طور می‌بینم.", af:"Ek sien dit presies dieselfde." }},
    { de: "Das ist eine gute Idee.", t:{ ua:"Це хороша ідея.", tr:"Bu iyi bir fikir.", so:"Taasi waa fikrad wanaagsan.", fa:"این یک ایدهٔ خوب است.", af:"Dit is ’n goeie idee." }},
    { de: "Ich habe die gleiche Meinung wie du.", t:{ ua:"Я маю таку ж думку, як і ти.", tr:"Seninle aynı fikirdeyim.", so:"Waxaan qabaa isla fikraddaada.", fa:"من هم‌عقیدهٔ تو هستم.", af:"Ek het dieselfde mening as jy." }},
    { de: "Ich verstehe, wie du das meinst.", t:{ ua:"Я розумію, що ти маєш на увазі.", tr:"Ne demek istediğini anlıyorum.", so:"Waan fahmay waxa aad ula jeedo.", fa:"می‌فهمم منظورت چیست.", af:"Ek verstaan wat jy bedoel." }},
    { de: "Da bin ich ganz deiner Meinung.", t:{ ua:"Тут я повністю з тобою згоден(на).", tr:"Bu konuda tamamen seninle aynı fikirdeyim.", so:"Arrintan si buuxda ayaan kugu raacsanahay.", fa:"در این مورد کاملاً با تو هم‌عقیده‌ام.", af:"Daar stem ek heeltemal saam met jou." }},
    { de: "Da hast du recht.", t:{ ua:"Ти маєш рацію.", tr:"Haklısın.", so:"Waad saxantahay.", fa:"حق با توست.", af:"Jy is reg." }},
    { de: "Das sehe ich auch so.", t:{ ua:"Я також так вважаю.", tr:"Ben de öyle düşünüyorum.", so:"Aniguna sidaas ayaan u arkaa.", fa:"من هم همین‌طور فکر می‌کنم.", af:"Ek sien dit ook so." }},
    { de: "Ich denke, das geht.", t:{ ua:"Я думаю, це можливо.", tr:"Bence bu olur.", so:"Waxaan u maleynayaa inay suurtagal tahay.", fa:"فکر می‌کنم ممکن است.", af:"Ek dink dit sal werk." }},
    { de: "Ich finde, dass das eine gute Lösung ist.", t:{ ua:"Я вважаю, що це хороше рішення.", tr:"Bence bu iyi bir çözüm.", so:"Waxaan u arkaa in tani tahay xal wanaagsan.", fa:"فکر می‌کنم این راه‌حل خوبی است.", af:"Ek dink dit is ’n goeie oplossing." }},
    { de: "Meiner Meinung nach ist das richtig.", t:{ ua:"На мою думку, це правильно.", tr:"Bence bu doğru.", so:"Aragtidayda waa sax.", fa:"به نظر من این درست است.", af:"Na my mening is dit reg." }},
    { de: "Meiner Ansicht nach ist das sinnvoll.", t:{ ua:"На мою думку, це має сенс.", tr:"Bana göre bu mantıklı.", so:"Aragtidayda tani waa macquul.", fa:"به عقیدهٔ من این منطقی است.", af:"Na my siening is dit sinvol." }},
    { de: "Ich glaube, dass das funktioniert.", t:{ ua:"Я думаю, що це спрацює.", tr:"Bence bu işe yarayacak.", so:"Waxaan aaminsanahay inay shaqayn doonto.", fa:"فکر می‌کنم این کار خواهد کرد.", af:"Ek glo dit sal werk." }},
    { de: "Für mich ist das eine gute Idee.", t:{ ua:"Для мене це хороша ідея.", tr:"Benim için bu iyi bir fikir.", so:"Aniga ahaan tani waa fikrad wanaagsan.", fa:"برای من این یک ایدهٔ خوب است.", af:"Vir my is dit ’n goeie idee." }},
    { de: "Ich halte es für sinnvoll, das zu machen.", t:{ ua:"Я вважаю доцільним це зробити.", tr:"Bunu yapmayı mantıklı buluyorum.", so:"Waxaan u arkaa inay macquul tahay in tan la sameeyo.", fa:"من انجام این کار را منطقی می‌دانم.", af:"Ek beskou dit as sinvol om dit te doen." }}
  ],

  ref: [
    { de: "Das passt mir leider nicht.", t: { ua: "Мені не підходить.", tr: "Bana uymuyor.", so: "Ii ma shaqaynayso.", fa: "برام مناسب نیست.", af: "Dit pas my ongelukkig nie." }},
    { de: "Ich habe da schon etwas vor.", t: { ua: "Я зайнятий.", tr: "Planım var.", so: "Waxaan hayaa qorshe.", fa: "برنامه دارم.", af: "Ek het reeds planne." }},
    { de: "Vielleicht ein anderes Mal.", t: { ua: "Іншим разом.", tr: "Başka zaman.", so: "Waqti kale.", fa: "یک وقت دیگر.", af: "Miskien ’n ander keer." }},
    { de: "Das wird schwierig.", t: { ua: "Це складно.", tr: "Zor olacak.", so: "Way adkaan doontaa.", fa: "سخت است.", af: "Dit gaan moeilik wees." }},
    { de: "Ich schaffe es zeitlich nicht.", t: { ua: "Не встигаю.", tr: "Vaktim yok.", so: "Waqti ma hayo.", fa: "وقت ندارم.", af: "Ek het nie tyd nie." }},
    { de: "Das passt mir nicht gut.", t: { ua: "Мені зовсім не підходить.", tr: "Hiç uymuyor.", so: "Sikama aha.", fa: "کاملاً مناسب نیست.", af: "Dit pas my glad nie." }},
    { de: "Leider habe ich andere Pläne.", t: { ua: "На жаль, інші плани.", tr: "Maalesef başka planlarım var.", so: "Nasiib darro, qorshayaal kale.", fa: "متأسفانه برنامه دیگری دارم.", af: "Ongelukkig het ek ander planne." }},
    { de: "Ich kann nicht kommen.", t: { ua: "Не можу прийти.", tr: "Gelemem.", so: "Ma imaan karo.", fa: "نمی‌توانم بیایم.", af: "Ek kan nie kom nie." }},
    { de: "Das ist leider nicht möglich.", t: { ua: "На жаль, це неможливо.", tr: "Maalesef mümkün değil.", so: "Nasiib darro ma suurtagal.", fa: "متأسفانه ممکن نیست.", af: "Dit is ongelukkig nie moontlik nie." }},
    { de: "Es tut mir leid, ich kann nicht.", t: { ua: "Вибачте, я не можу.", tr: "Üzgünüm, yapamam.", so: "Waan ka xumahay, ma qaban karo.", fa: "متأسفم، نمی‌توانم.", af: "Ek is jammer, ek kan nie." }},
    { de: "Ich muss absagen.", t: { ua: "Мушу відмінити.", tr: "İptal etmem gerekiyor.", so: "Waan joojinayaa.", fa: "باید لغو کنم.", af: "Ek moet afsê." }},
    { de: "Ich bin verhindert.", t: { ua: "Я зайнятий.", tr: "Müsait değilim.", so: "Ma awoodo.", fa: "مشغولم.", af: "Ek is verhinderd." }},
    { de: "Das klappt leider nicht.", t: { ua: "На жаль, не вийде.", tr: "Maalesef işe yaramıyor.", so: "Nasiib darro ma shaqeynayo.", fa: "متأسفانه درست نمی‌شود.", af: "Dit werk ongelukkig nie." }},
    { de: "Es passt leider nicht.", t: { ua: "На жаль, не підходить.", tr: "Maalesef uymuyor.", so: "Nasiib darro ma habboona.", fa: "متأسفانه مناسب نیست.", af: "Dit pas ongelukkig nie." }},
    { de: "Ich habe leider keine Zeit.", t: { ua: "На жаль, немає часу.", tr: "Maalesef vaktim yok.", so: "Nasiib darro waqti ma hayo.", fa: "متأسفانه وقت ندارم.", af: "Ek het ongelukkig geen tyd nie." }},
    { de: "Leider kann ich nicht teilnehmen.", t: { ua: "На жаль, не можу брати участь.", tr: "Maalesef katılamam.", so: "Nasiib darro ma ka qayb gali karo.", fa: "متأسفانه نمی‌توانم شرکت کنم.", af: "Ongelukkig kan ek nie deelneem nie." }},
    { de: "Es ist mir leider nicht möglich.", t: { ua: "На жаль, для мене це неможливо.", tr: "Maalesef benim için mümkün değil.", so: "Nasiib darro aniga ma suurtagal.", fa: "متأسفانه برای من ممکن نیست.", af: "Dit is ongelukkig nie moontlik vir my nie." }},
    { de: "Ich habe andere Verpflichtungen.", t: { ua: "У мене інші обов’язки.", tr: "Başka yükümlülüklerim var.", so: "Waxqabadyo kale ayaan hayaa.", fa: "متعهد به کار دیگری هستم.", af: "Ek het ander verpligtinge." }},
    { de: "Das passt mir terminlich nicht.", t: { ua: "Не підходить за часом.", tr: "Zamanlama olarak uymuyor.", so: "Waqti ahaan ma habboona.", fa: "زمانش مناسب نیست.", af: "Dit pas nie by my skedule nie." }},
    { de: "Ich bin an diesem Tag beschäftigt.", t: { ua: "В цей день зайнятий.", tr: "O gün meşgulüm.", so: "Maalin taas waxaan ku mashquulsanahay.", fa: "در آن روز مشغولم.", af: "Ek is besig daardie dag." }},
    { de: "Das lässt sich leider nicht einrichten.", t: { ua: "На жаль, не можна організувати.", tr: "Maalesef ayarlanamıyor.", so: "Nasiib darro ma qaban karo.", fa: "متأسفانه نمی‌شود تنظیم کرد.", af: "Dit kan ongelukkig nie gereël word nie." }},
    { de: "Ich bin an diesem Termin verhindert.", t: { ua: "На цей час зайнятий.", tr: "O tarihte müsait değilim.", so: "Waqtigaas ma awoodo.", fa: "در این زمان نمی‌توانم.", af: "Ek is op daardie afspraak verhinderd." }},
    { de: "Ich muss ablehnen.", t: { ua: "Мушу відмовитись.", tr: "Reddetmem gerekiyor.", so: "Waan diidayaa.", fa: "باید رد کنم.", af: "Ek moet weier." }},
    { de: "Das ist nicht machbar.", t: { ua: "Це неможливо.", tr: "Bu mümkün değil.", so: "Ma suurtagal.", fa: "این امکان‌پذیر نیست.", af: "Dit is nie uitvoerbaar nie." }},
    { de: "Ich kann leider nicht zusagen.", t: { ua: "На жаль, не можу погодитись.", tr: "Maalesef onaylayamıyorum.", so: "Nasiib darro ma xaqiijin karo.", fa: "متأسفانه نمی‌توانم موافقت کنم.", af: "Ek kan ongelukkig nie bevestig nie." }},
    { de: "Ich muss es absagen.", t: { ua: "Мушу відмінити.", tr: "İptal etmem gerekiyor.", so: "Waan joojinayaa.", fa: "باید لغو کنم.", af: "Ek moet dit afsê." }},
    { de: "Das ist terminlich ungünstig.", t: { ua: "Час не підходить.", tr: "Zamanlama uygun değil.", so: "Waqti ahaan ma habboona.", fa: "زمان مناسب نیست.", af: "Dit is skeduleer ongunstig." }},
    { de: "Leider passt es nicht.", t: { ua: "На жаль, не підходить.", tr: "Maalesef uymuyor.", so: "Nasiib darro ma habboona.", fa: "متأسفانه مناسب نیست.", af: "Ongelukkig pas dit nie." }},
    { de: "Es kommt mir nicht gelegen.", t: { ua: "Мені це не зручно.", tr: "Bana uygun değil.", so: "Uma habboona.", fa: "برایم مناسب نیست.", af: "Dit pas my nie goed nie." }},
    { de: "Ich habe bereits Pläne.", t: { ua: "В мене вже є плани.", tr: "Zaten planlarım var.", so: "Waxaan hore u qorsheeyay.", fa: "قبلاً برنامه‌ریزی کرده‌ام.", af: "Ek het reeds planne." }},
    { de: "Es passt mir terminlich nicht gut.", t: { ua: "Часом не підходить.", tr: "Zamanlama olarak uymuyor.", so: "Waqti ahaan ma habboona.", fa: "زمانش مناسب نیست.", af: "Dit pas nie goed by my skedule nie." }},
    { de: "Ich bin anderweitig beschäftigt.", t: { ua: "Я зайнятий іншими справами.", tr: "Başka bir işle meşgulüm.", so: "Waxaan ku mashquulsanahay arrimo kale.", fa: "مشغول کار دیگری هستم.", af: "Ek is elders besig." }},
    { de: "Ich kann an diesem Tag nicht.", t: { ua: "У цей день не можу.", tr: "O gün gelemem.", so: "Maalintaas ma imaan karo.", fa: "در آن روز نمی‌توانم.", af: "Ek kan nie daardie dag nie." }},
    { de: "Das ist nicht möglich.", t: { ua: "Це неможливо.", tr: "Bu mümkün değil.", so: "Ma suurtagal.", fa: "این امکان‌پذیر نیست.", af: "Dit is nie moontlik nie." }},
    { de: "Leider habe ich keine Kapazität.", t: { ua: "На жаль, немає можливості.", tr: "Maalesef kapasitem yok.", so: "Nasiib darro ma awoodo.", fa: "متأسفانه ظرفیت ندارم.", af: "Ongelukkig het ek nie kapasiteit nie." }},
    { de: "Das ist terminlich problematisch.", t: { ua: "Час проблемний.", tr: "Zamanlama sorunlu.", so: "Waqti ahaan waa dhibaato.", fa: "زمان مشکلی دارد.", af: "Dit is skeduleer problematies." }},
    { de: "Ich bin an dem Tag nicht verfügbar.", t: { ua: "У цей день недоступний.", tr: "O gün müsait değilim.", so: "Maalintaas ma heli karo.", fa: "در آن روز در دسترس نیستم.", af: "Ek is nie beskikbaar daardie dag nie." }},
    { de: "Ich muss absagen, leider.", t: { ua: "Мушу відмінити, на жаль.", tr: "Maalesef iptal etmem gerekiyor.", so: "Waan ka xumahay, waan joojinayaa.", fa: "متأسفانه باید لغو کنم.", af: "Ek moet ongelukkig afsê." }},
    { de: "Ich habe einen anderen Termin.", t: { ua: "У мене інша зустріч.", tr: "Başka bir randevum var.", so: "Qorshe kale ayaan hayaa.", fa: "قرار دیگری دارم.", af: "Ek het ’n ander afspraak." }},
    { de: "Ich kann nicht zusagen.", t: { ua: "Не можу погодитися.", tr: "Onaylayamam.", so: "Ma xaqiijin karo.", fa: "نمی‌توانم موافقت کنم.", af: "Ek kan nie bevestig nie." }},
    { de: "Das finde ich nicht so gut.", t:{ ua:"Я вважаю, що це не дуже добре.", tr:"Bunu o kadar iyi bulmuyorum.", so:"Taas si fiican uma arko.", fa:"به نظرم این خیلی خوب نیست.", af:"Ek dink dit is nie so goed nie." }},
    { de: "Ich habe eine andere Meinung.", t:{ ua:"Я маю іншу думку.", tr:"Farklı bir görüşüm var.", so:"Waxaan qabaa fikrad kale.", fa:"من نظر دیگری دارم.", af:"Ek het ’n ander mening." }},
    { de: "Ich denke anders.", t:{ ua:"Я думаю інакше.", tr:"Ben farklı düşünüyorum.", so:"Si kale ayaan u fikirayaa.", fa:"من طور دیگری فکر می‌کنم.", af:"Ek dink anders." }},
    { de: "Leider kann ich nicht zustimmen.", t:{ ua:"На жаль, я не можу погодитися.", tr:"Maalesef katılamıyorum.", so:"Nasiib darro ma raaci karo.", fa:"متأسفانه نمی‌توانم موافقت کنم.", af:"Ongelukkig kan ek nie saamstem nie." }},
    { de: "Ich habe Bedenken.", t:{ ua:"У мене є сумніви.", tr:"Endişelerim var.", so:"Waxaan qabaa walaac.", fa:"نگرانی‌هایی دارم.", af:"Ek het bedenkinge." }},
    { de: "Das ist gut, aber etwas anderes wäre besser.", t:{ ua:"Це добре, але щось інше було б краще.", tr:"Bu iyi, ama başka bir şey daha iyi olurdu.", so:"Waa fiican, laakiin wax kale ayaa ka fiicnaan lahaa.", fa:"این خوب است، اما چیز دیگری بهتر است.", af:"Dit is goed, maar iets anders sou beter wees." }},
    { de: "Ich sehe das anders.", t:{ ua:"Я бачу це інакше.", tr:"Ben bunu farklı görüyorum.", so:"Si kale ayaan u arkaa.", fa:"من این را طور دیگری می‌بینم.", af:"Ek sien dit anders." }},
    { de: "Ich bin nicht ganz einverstanden.", t:{ ua:"Я не зовсім згоден(на).", tr:"Tam olarak katılmıyorum.", so:"Si buuxda uma oggoli.", fa:"کاملاً موافق نیستم.", af:"Ek stem nie heeltemal saam nie." }},
    { de: "Hier muss ich widersprechen.", t:{ ua:"Тут я мушу заперечити.", tr:"Burada itiraz etmeliyim.", so:"Halkan waa inaan diido.", fa:"اینجا باید مخالفت کنم.", af:"Hier moet ek verskil." }},
    { de: "Ich stimme nicht zu.", t:{ ua:"Я не згоден(на).", tr:"Katılmıyorum.", so:"Ma oggoli.", fa:"موافق نیستم.", af:"Ek stem nie saam nie." }},
    { de: "Ich bin nicht so sicher.", t:{ ua:"Я не дуже впевнений(а).", tr:"O kadar emin değilim.", so:"Si buuxda uma hubin.", fa:"چندان مطمئن نیستم.", af:"Ek is nie so seker nie." }}
  ],

par: [
  { de: "Jein.", t: { ua: "І так, і ні.", tr: "Hem evet hem hayır.", so: "Haa iyo Maya.", fa: "هم آره هم نه.", af: "Ja en nee." }},
  { de: "Das kommt darauf an.", t: { ua: "Це залежить від обставин.", tr: "Duruma göre değişir.", so: "Way ku xirantahay.", fa: "بستگی دارد.", af: "Dit hang af." }},
  { de: "Eigentlich schon, aber...", t: { ua: "Взагалі-то так, але...", tr: "Aslında evet ama...", so: "Dhab ahaan haa, laakiin...", fa: "در واقع بله، اما...", af: "Eintlik wel, maar..." }},
  { de: "Im Prinzip ja.", t: { ua: "В принципі так.", tr: "Prensipte evet.", so: "Mabda' ahaan haa.", fa: "در اصل بله.", af: "In beginsel ja." }},
  { de: "Vielleicht, ich bin не sicher.", t: { ua: "Можливо, я не впевнений.", tr: "Belki, emin değilim.", so: "Malaha, ma hubo.", fa: "شاید، مطمئن نیستم.", af: "Miskien, ek is nie seker nie." }},
  { de: "Das ist teilweise richtig.", t: { ua: "Це частково правильно.", tr: "Bu kısmen doğru.", so: "Taas waa sax qayb ahaan.", fa: "این تا حدی درست است.", af: "Dit is gedeeltelik korrek." }},
  { de: "Ich muss mir das noch überlegen.", t: { ua: "Мені треба ще подумати.", tr: "Bunu düşünmem lazım.", so: "Waa inaan ka fikiro.", fa: "باید در موردش فکر کنم.", af: "Ek moet nog daaroor dink." }},
  { de: "Mal schauen.", t: { ua: "Побачимо.", tr: "Bakarız.", so: "Aan aragno.", fa: "ببینیم چه می‌شود.", af: "Ons sal sien." }},
  { de: "Bis zu einem gewissen Punkt ja.", t: { ua: "До певної міри так.", tr: "Bir noktaya kadar evet.", so: "Ilaa heer xaqiiqdii haa.", fa: "تا حدودی بله.", af: "Tot op ’n punt, ja." }},
  { de: "Das klingt interessant, aber...", t: { ua: "Це звучить цікаво, але...", tr: "Kulağa ilginç geliyor ama...", so: "Taas waxay u egtahay mid xiiso leh, laakiin...", fa: "جالب به نظر می‌رسد، اما...", af: "Dit klink interessant, maar..." }},
  { de: "Ich stimme dir teilweise zu.", t:{ ua:"Я частково з тобою згоден(на).", tr:"Sana kısmen katılıyorum.", so:"Qayb ahaan waan kugu raacsanahay.", fa:"تا حدی با تو موافقم.", af:"Ek stem gedeeltelik saam met jou." }},
  { de: "Da hast du teilweise recht.", t:{ ua:"Ти частково маєш рацію.", tr:"Kısmen haklısın.", so:"Qayb ahaan waad saxantahay.", fa:"تا حدی حق با توست.", af:"Jy is gedeeltelik reg." }},
  { de: "Im Prinzip ja, aber …", t:{ ua:"В принципі так, але …", tr:"Prensipte evet, ama …", so:"Mabda’ ahaan haa, laakiin …", fa:"در اصل بله، اما …", af:"In beginsel ja, maar …" }},
  { de: "Grundsätzlich bin ich einverstanden, aber …", t:{ ua:"Загалом я згоден(на), але …", tr:"Genel olarak katılıyorum, ama …", so:"Guud ahaan waan oggolahay, laakiin …", fa:"در کل موافقم، اما …", af:"Oor die algemeen stem ek saam, maar …" }},
  { de: "Ich verstehe deinen Punkt, aber …", t:{ ua:"Я розумію твою думку, але …", tr:"Söylemek istediğini anlıyorum, ama …", so:"Waxaan fahmay qodobkaaga, laakiin …", fa:"نکته‌ات را می‌فهمم، اما …", af:"Ek verstaan jou punt, maar …" }},
  { de: "Da bin ich nur teilweise deiner Meinung.", t:{ ua:"Тут я лише частково з тобою згоден(на).", tr:"Bu konuda sadece kısmen katılıyorum.", so:"Arrintan qayb ahaan ayaan kugu raacsanahay.", fa:"در این مورد فقط تا حدی با تو هم‌عقیده‌ام.", af:"Daar stem ek net gedeeltelik saam met jou." }},
  { de: "Teilweise sehe ich das auch so.", t:{ ua:"Частково я теж так вважаю.", tr:"Kısmen ben de öyle düşünüyorum.", so:"Qayb ahaan aniguna sidaas ayaan u arkaa.", fa:"تا حدی من هم همین‌طور می‌بینم.", af:"Gedeeltelik sien ek dit ook so." }},
  { de: "Das stimmt, allerdings …", t:{ ua:"Це правда, однак …", tr:"Bu doğru, ancak …", so:"Taasi waa sax, si kastaba …", fa:"این درست است، با این حال …", af:"Dit is waar, maar …" }},
  { de: "Ja, aber man sollte auch bedenken, dass …", t:{ ua:"Так, але слід також врахувати, що …", tr:"Evet, ama şunu da düşünmek gerekir ki …", so:"Haa, laakiin waa in sidoo kale la tixgeliyaa in …", fa:"بله، اما باید در نظر گرفت که …", af:"Ja, maar ’n mens moet ook in ag neem dat …" }},
  { de: "Ich sehe deinen Standpunkt, dennoch …", t:{ ua:"Я бачу твою позицію, проте …", tr:"Bakış açını görüyorum, yine de …", so:"Waxaan arkaa aragtidaada, haddana …", fa:"دیدگاهت را می‌بینم، با این حال …", af:"Ek sien jou standpunt, tog …" }},
  { de: "Im Grossen und Ganzen ja, aber …", t:{ ua:"В цілому так, але …", tr:"Genel olarak evet, ama …", so:"Guud ahaan haa, laakiin …", fa:"در کل بله، اما …", af:"Oor die algemeen ja, maar …" }},
  { de: "Einerseits ja, andererseits …", t:{ ua:"З одного боку так, з іншого …", tr:"Bir yandan evet, diğer yandan …", so:"Dhinac haa, dhinac kale …", fa:"از یک طرف بله، از طرف دیگر …", af:"Aan die een kant ja, aan die ander kant …" }},
  { de: "Ich bin nicht ganz dagegen.", t:{ ua:"Я не повністю проти.", tr:"Tamamen karşı değilim.", so:"Si buuxda uga soo horjeedo ma ihi.", fa:"کاملاً مخالف نیستم.", af:"Ek is nie heeltemal daarteen nie." }},
  { de: "Das klingt vernünftig, aber …", t:{ ua:"Це звучить розумно, але …", tr:"Mantıklı geliyor, ama …", so:"Waxay u muuqataa macquul, laakiin …", fa:"منطقی به نظر می‌رسد، اما …", af:"Dit klink redelik, maar …" }},
  { de: "Ich kann dem teilweise zustimmen.", t:{ ua:"Я можу частково погодитися.", tr:"Buna kısmen katılabilirim.", so:"Qayb ahaan waan ku raaci karaa.", fa:"تا حدی می‌توانم موافقت کنم.", af:"Ek kan gedeeltelik saamstem." }},
  { de: "Vielleicht hast du recht, aber …", t:{ ua:"Можливо, ти маєш рацію, але …", tr:"Belki haklısın, ama …", so:"Waxaa laga yaabaa inaad saxantahay, laakiin …", fa:"شاید حق با تو باشد، اما …", af:"Miskien is jy reg, maar …" }},
  { de: "Ich bin mir nicht ganz sicher, aber es könnte sein.", t:{ ua:"Я не зовсім впевнений(а), але це можливо.", tr:"Tam emin değilim, ama olabilir.", so:"Si buuxda uma hubin, laakiin way dhici kartaa.", fa:"کاملاً مطمئن نیستم، اما ممکن است.", af:"Ek is nie heeltemal seker nie, maar dit kan wees." }},
  { de: "Das kann ich nachvollziehen, trotzdem …", t:{ ua:"Я можу це зрозуміти, все ж …", tr:"Bunu anlayabiliyorum, yine de …", so:"Waan fahmi karaa, haddana …", fa:"می‌توانم درک کنم، با این حال …", af:"Ek kan dit verstaan, tog …" }},
  { de: "Ich stimme im Grunde zu.", t:{ ua:"По суті, я згоден(на).", tr:"Temelde katılıyorum.", so:"Asal ahaan waan ku raacsanahay.", fa:"در اصل موافقم.", af:"Ek stem basies saam." }},
  { de: "Nicht ganz, aber teilweise schon.", t:{ ua:"Не зовсім, але частково так.", tr:"Tam değil, ama kısmen evet.", so:"Si buuxda ma aha, laakiin qayb ahaan haa.", fa:"نه کاملاً، اما تا حدی بله.", af:"Nie heeltemal nie, maar gedeeltelik wel." }},
  { de: "Ich teile deine Meinung nur zum Teil.", t:{ ua:"Я поділяю твою думку лише частково.", tr:"Görüşünü sadece kısmen paylaşıyorum.", so:"Fikraddaada qayb ahaan ayaan wadaagaa.", fa:"نظر تو را فقط تا حدی قبول دارم.", af:"Ek deel jou mening net gedeeltelik." }},
  { de: "Das sehe ich ähnlich, aber …", t:{ ua:"Я бачу це подібно, але …", tr:"Benzer şekilde görüyorum, ama …", so:"Si la mid ah ayaan u arkaa, laakiin …", fa:"تقریباً همین‌طور می‌بینم، اما …", af:"Ek sien dit soortgelyk, maar …" }},
  { de: "In gewisser Weise ja.", t:{ ua:"У певному сенсі так.", tr:"Bir bakıma evet.", so:"Qaab ahaan haa.", fa:"به نوعی بله.", af:"In ’n sekere sin ja." }},
  { de: "Man kann dem zustimmen, jedoch …", t:{ ua:"З цим можна погодитися, проте …", tr:"Buna katılınabilir, ancak …", so:"Waa lagu raaci karaa, hase yeeshee …", fa:"می‌توان با آن موافقت کرد، اما …", af:"’n Mens kan saamstem, maar …" }},
  { de: "Das stimmt teilweise.", t:{ ua:"Це частково правда.", tr:"Bu kısmen doğru.", so:"Taas qayb ahaan waa sax.", fa:"این تا حدی درست است.", af:"Dit is gedeeltelik waar." }},
  { de: "Ich bin da etwas zwiegespalten.", t:{ ua:"Я тут трохи вагаюся.", tr:"Bu konuda kararsızım.", so:"Arrintan waan ka laba labaynayaa.", fa:"در این مورد مرددم.", af:"Ek is daaroor ’n bietjie verdeeld." }},
  { de: "Ich kann beide Seiten verstehen.", t:{ ua:"Я можу зрозуміти обидві сторони.", tr:"Her iki tarafı da anlayabiliyorum.", so:"Labada dhinacba waan fahmi karaa.", fa:"می‌توانم هر دو طرف را درک کنم.", af:"Ek kan albei kante verstaan." }},
  { de: "Das ist nicht falsch, aber …", t:{ ua:"Це не неправильно, але …", tr:"Bu yanlış değil, ama …", so:"Tani khalad ma aha, laakiin …", fa:"این اشتباه نیست، اما …", af:"Dit is nie verkeerd nie, maar …" }},
  { de: "Ich bin da geteilter Meinung.", t:{ ua:"Я маю змішані почуття щодо цього.", tr:"Bu konuda ikiye bölünmüş durumdayım.", so:"Arrintan fikradahaygu way kala qaybsan yihiin.", fa:"در این مورد نظر دوگانه دارم.", af:"Ek is daaroor verdeeld." }},
  { de: "Zum Teil ja, zum Teil nein.", t:{ ua:"Частково так, частково ні.", tr:"Kısmen evet, kısmen hayır.", so:"Qayb haa, qayb maya.", fa:"تا حدی بله، تا حدی نه.", af:"Gedeeltelik ja, gedeeltelik nee." }},
  { de: "Ich sehe Vorteile, aber auch Nachteile.", t:{ ua:"Я бачу переваги, але й недоліки.", tr:"Avantajlar görüyorum, ama dezavantajlar da var.", so:"Waxaan arkaa faa’iidooyin, laakiin sidoo kale qasaarooyin.", fa:"مزایا را می‌بینم، اما معایب هم هست.", af:"Ek sien voordele, maar ook nadele." }},
  { de: "Das ist ein guter Punkt, dennoch …", t:{ ua:"Це хороший аргумент, проте …", tr:"Bu iyi bir nokta, yine de …", so:"Waa qodob wanaagsan, haddana …", fa:"نکتهٔ خوبی است، با این حال …", af:"Dit is ’n goeie punt, tog …" }},
  { de: "Ich verstehe deine Argumente, aber …", t:{ ua:"Я розумію твої аргументи, але …", tr:"Argümanlarını anlıyorum, ama …", so:"Doodahaaga waan fahmay, laakiin …", fa:"استدلال‌هایت را می‌فهمم، اما …", af:"Ek verstaan jou argumente, maar …" }},
  { de: "Das könnte stimmen, allerdings …", t:{ ua:"Можливо, це так, однак …", tr:"Bu doğru olabilir, ancak …", so:"Way dhici kartaa inay sax tahay, hase yeeshee …", fa:"ممکن است درست باشد، اما …", af:"Dit kan waar wees, maar …" }},
  { de: "Ich bin nicht völlig überzeugt.", t:{ ua:"Я не повністю переконаний(а).", tr:"Tam olarak ikna olmadım.", so:"Si buuxda uma qancin.", fa:"کاملاً متقاعد نشده‌ام.", af:"Ek is nie heeltemal oortuig nie." }},
  { de: "Einverstanden, aber wir müssen noch überlegen.", t:{ ua:"Згоден(на), але нам ще потрібно подумати.", tr:"Kabul, ama hâlâ düşünmemiz gerekiyor.", so:"Waan oggolahay, laakiin weli waa inaan ka fikirnaa.", fa:"موافقم، اما هنوز باید فکر کنیم.", af:"Ek stem saam, maar ons moet nog daaroor dink." }}
],

  con: [
    { de: "Wie wäre es etwas später?", t: { ua: "Трохи пізніше?", tr: "Biraz sonra?", so: "Hadhow?", fa: "کمی دیرتر؟", af: "’n Bietjie later?" }},
    { de: "Können wir das verschieben?", t: { ua: "Можемо перенести?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Kan ons dit skuif?" }},
    { de: "Vielleicht an einem anderen Ort?", t: { ua: "В іншому місці?", tr: "Başka yerde?", so: "Meel kale?", fa: "جای دیگر؟", af: "Op ’n ander plek?" }},
    { de: "Lass uns einen anderen Tag nehmen.", t: { ua: "Інший день.", tr: "Başka gün.", so: "Maalin kale.", fa: "روز دیگر.", af: "’n Ander dag." }},
    { de: "Geht es dir morgen?", t: { ua: "Завтра зручно?", tr: "Yarın uygun mu?", so: "Berri ma u fiican?", fa: "فردا مناسب است؟", af: "Werk dit vir jou môre?" }},
    { de: "Wollen wir es verschieben?", t: { ua: "Переносимо?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Wil ons dit skuif?" }},
    { de: "Könnten wir später anfangen?", t: { ua: "Можемо пізніше почати?", tr: "Daha sonra başlayabilir miyiz?", so: "Ma dib u bilaabi karnaa?", fa: "می‌توانیم دیرتر شروع کنیم؟", af: "Kan ons later begin?" }},
    { de: "Passt es dir am Nachmittag?", t: { ua: "Вдень зручно?", tr: "Öğleden sonra uygun mu?", so: "Galab ma u fiican?", fa: "بعد از ظهر مناسب است؟", af: "Pas dit vir jou in die middag?" }},
    { de: "Sollen wir den Ort ändern?", t: { ua: "Змінити місце?", tr: "Yeri değiştirelim mi?", so: "Ma bedeliyaa goobta?", fa: "مکان را تغییر دهیم؟", af: "Moet ons die plek verander?" }},
    { de: "Wollen wir einen anderen Tag nehmen?", t: { ua: "Інший день вибрати?", tr: "Başka gün mü alalım?", so: "Maalin kale ma qaadnaa?", fa: "روز دیگری انتخاب کنیم؟", af: "Wil ons ’n ander dag neem?" }},
    { de: "Können wir es später machen?", t: { ua: "Можемо пізніше зробити?", tr: "Daha sonra yapabilir miyiz?", so: "Ma dib u sameyn karnaa?", fa: "می‌توانیم بعداً انجام دهیم؟", af: "Kan ons dit later doen?" }},
    { de: "Wie wäre es am Abend?", t: { ua: "Ввечері як?", tr: "Akşam nasıl?", so: "Fiidkii sidee?", fa: "شب چطور؟", af: "Hoe gaan dit saans?" }},
    { de: "Passt dir der Nachmittag?", t: { ua: "День підходить?", tr: "Öğleden sonra uygun mu?", so: "Galab ma ku habboon?", fa: "بعد از ظهر مناسب است؟", af: "Pas dit vir jou in die middag?" }},
    { de: "Sollen wir es verschieben?", t: { ua: "Перенести?", tr: "Erteleyelim mi?", so: "Ma dib u dhigno?", fa: "تعویق کنیم؟", af: "Moet ons dit skuif?" }},
    { de: "Können wir einen anderen Tag wählen?", t: { ua: "Інший день вибрати?", tr: "Başka gün seçebilir miyiz?", so: "Maalin kale dooran karnaa?", fa: "روز دیگری انتخاب کنیم؟", af: "Kan ons ’n ander dag kies?" }},
    { de: "Ist später für dich möglich?", t: { ua: "Пізніше можливо для тебе?", tr: "Daha sonra senin için mümkün mü?", so: "Maka dambe ma kuu shaqeyn karaa?", fa: "بعداً برایت ممکن است؟", af: "Is later moontlik vir jou?" }},
    { de: "Sollen wir den Termin verschieben?", t: { ua: "Перенести зустріч?", tr: "Randevuyu erteleyelim mi?", so: "Ma dib u dhigno ballanta?", fa: "جلسه را عقب بیندازیم؟", af: "Moet ons die afspraak skuif?" }},
    { de: "Passt es dir später?", t: { ua: "Пізніше зручно?", tr: "Daha sonra uygun mu?", so: "Maka dambe ma u fiican?", fa: "بعداً مناسب است؟", af: "Pas dit vir jou later?" }},
    { de: "Können wir einen anderen Ort nehmen?", t: { ua: "Взяти інше місце?", tr: "Başka bir yer alabilir miyiz?", so: "Ma meel kale qaadnaa?", fa: "مکان دیگری انتخاب کنیم؟", af: "Kan ons ’n ander plek neem?" }},
    { de: "Wollen wir die Uhrzeit ändern?", t: { ua: "Змінити час?", tr: "Saatini değiştirelim mi?", so: "Ma bedelnaa waqtiga?", fa: "ساعت را تغییر دهیم؟", af: "Wil ons die tyd verander?" }},
    { de: "Vielleicht später?", t: { ua: "Можливо пізніше?", tr: "Belki sonra?", so: "Malaha dambe?", fa: "شاید بعداً؟", af: "Miskien later?" }},
    { de: "Können wir die Zeit ändern?", t: { ua: "Можемо змінити час?", tr: "Zamanı değiştirebilir miyiz?", so: "Ma bedelnaa waqtiga?", fa: "می‌توانیم زمان را تغییر دهیم؟", af: "Kan ons die tyd verander?" }},
    { de: "Wie wäre es morgen?", t: { ua: "Завтра як?", tr: "Yarın nasıl?", so: "Berri sidee?", fa: "فردا چطور؟", af: "Hoe gaan dit môre?" }},
    { de: "Können wir später sprechen?", t: { ua: "Можемо пізніше поговорити?", tr: "Daha sonra konuşabilir miyiz?", so: "Ma dib u hadli karnaa?", fa: "می‌توانیم بعداً صحبت کنیم؟", af: "Kan ons later praat?" }},
    { de: "Passt dir ein anderer Tag?", t: { ua: "Інший день підходить?", tr: "Başka gün uygun mu?", so: "Maalin kale ma ku habboon?", fa: "روز دیگری مناسب است؟", af: "Pas dit vir jou op ’n ander dag?" }},
    { de: "Wollen wir einen späteren Termin?", t: { ua: "Пізніша зустріч?", tr: "Daha sonraki bir randevu mu?", so: "Ballan dambe ma rabnaa?", fa: "جلسه دیرتر؟", af: "Wil ons ’n later afspraak hê?" }},
    { de: "Geht es dir morgen Nachmittag?", t: { ua: "Завтра вдень зручно?", tr: "Yarın öğleden sonra uygun mu?", so: "Berri galab ma u fiican?", fa: "بعد از ظهر فردا مناسب است؟", af: "Werk dit vir jou môre middag?" }},
    { de: "Können wir es auf morgen verschieben?", t: { ua: "Перенести на завтра?", tr: "Yarına erteleyebilir miyiz?", so: "Ma berri u dhigno?", fa: "می‌توانیم به فردا منتقل کنیم؟", af: "Kan ons dit na môre skuif?" }},
    { de: "Vielleicht an einem anderen Tag?", t: { ua: "Можливо інший день?", tr: "Belki başka bir gün?", so: "Malaha maalin kale?", fa: "شاید روز دیگری؟", af: "Miskien op ’n ander dag?" }},
    { de: "Wie wäre es später am Tag?", t: { ua: "Пізніше протягом дня?", tr: "Günün ilerleyen saatleri nasıl?", so: "Maalin dambe?", fa: "بعداً در طول روز؟", af: "Hoe gaan dit later daardie dag?" }},
    { de: "Passt es dir morgen?", t: { ua: "Завтра підходить?", tr: "Yarın uygun mu?", so: "Berri ma ku habboon?", fa: "فردا مناسب است؟", af: "Pas dit vir jou môre?" }},
    { de: "Sollen wir den Termin verschieben?", t: { ua: "Перенести зустріч?", tr: "Randevuyu erteleyelim mi?", so: "Ma dib u dhigno ballanta?", fa: "جلسه را عقب بیندازیم؟", af: "Moet ons die afspraak skuif?" }},
    { de: "Können wir später anfangen?", t: { ua: "Можемо пізніше почати?", tr: "Daha sonra başlayabilir miyiz?", so: "Ma dib u bilaabi karnaa?", fa: "می‌توانیم دیرتر شروع کنیم؟", af: "Kan ons later begin?" }},
    { de: "Vielleicht morgen?", t: { ua: "Можливо завтра?", tr: "Belki yarın?", so: "Malaha berri?", fa: "شاید فردا؟", af: "Miskien môre?" }},
    { de: "Wie sieht es morgen aus?", t: { ua: "Завтра як справи?", tr: "Yarın nasıl görünüyor?", so: "Berri sidee tahay?", fa: "فردا چطور است؟", af: "Hoe lyk dit môre?" }},
    { de: "Sollen wir die Uhrzeit ändern?", t: { ua: "Змінити час?", tr: "Saatini değiştirelim mi?", so: "Ma bedelnaa waqtiga?", fa: "ساعت را تغییر دهیم؟", af: "Wil ons die tyd verander?" }},
    { de: "Geht es dir später?", t: { ua: "Пізніше підходить?", tr: "Daha sonra uygun mu?", so: "Maka dambe ma kuu fiican?", fa: "بعداً مناسب است؟", af: "Pas dit vir jou later?" }},
    { de: "Können wir es verschieben?", t: { ua: "Можемо перенести?", tr: "Erteleyebilir miyiz?", so: "Ma dib u dhigno?", fa: "می‌توانیم منتقل کنیم؟", af: "Kan ons dit skuif?" }},
    { de: "Wie wäre es nächste Woche?", t: { ua: "Наступного тижня як?", tr: "Gelecek hafta nasıl?", so: "Toddobaadka dambe sidee?", fa: "هفته آینده چطور؟", af: "Hoe gaan dit volgende week?" }},
    { de: "Passt dir später am Tag?", t: { ua: "Пізніше протягом дня підходить?", tr: "Günün ilerleyen saatleri uygun mu?", so: "Maalin dambe ma ku habboon?", fa: "بعداً در طول روز مناسب است؟", af: "Pas dit vir jou later daardie dag?" }},
    { de: "Sollen wir einen späteren Zeitpunkt nehmen?", t: { ua: "Взяти пізніший час?", tr: "Daha sonraki bir zaman mı alalım?", so: "Waqti dambe ma qaadnaa?", fa: "زمان دیرتر انتخاب کنیم؟", af: "Moet ons ’n later tyd neem?" }},
    { de: "Können wir auf später verschieben?", t: { ua: "Перенести на пізніше?", tr: "Daha sonra erteleyebilir miyiz?", so: "Ma dib u dhigno?", fa: "می‌توانیم به بعد منتقل کنیم؟", af: "Kan ons na later skuif?" }},
    { de: "Vielleicht später am Tag?", t: { ua: "Можливо пізніше протягом дня?", tr: "Günün ilerleyen saatlerinde belki?", so: "Malaha maalin dambe?", fa: "شاید بعداً در طول روز؟", af: "Miskien later daardie dag?" }},
    { de: "Stattdessen sollten wir etwas anderes machen.", t:{ ua:"Натомість нам слід зробити щось інше.", tr:"Bunun yerine başka bir şey yapmalıyız.", so:"Halkii, waa inaan wax kale sameynaa.", fa:"در عوض باید کار دیگری انجام دهیم.", af:"Ons moet eerder iets anders doen." }},
    { de: "Eine andere Möglichkeit wäre, etwas anderes zu machen.", t:{ ua:"Інша можливість — зробити щось інше.", tr:"Başka bir seçenek başka bir şey yapmak olurdu.", so:"Fursad kale waxay noqon lahayd inaan wax kale sameyno.", fa:"یک امکان دیگر این است که کار دیگری انجام دهیم.", af:"’n Ander moontlikheid sou wees om iets anders te doen." }},
    { de: "Ich hätte da eine Alternative.", t:{ ua:"У мене є альтернатива.", tr:"Bir alternatifim var.", so:"Waxaan hayaa beddel kale.", fa:"یک گزینهٔ جایگزین دارم.", af:"Ek het ’n alternatief." }},
    { de: "Sollten wir nicht lieber etwas anderes machen?", t:{ ua:"Може, нам краще зробити щось інше?", tr:"Başka bir şey yapmayı tercih etsek olmaz mı?", so:"Miyaynaan dooran inaan wax kale sameyno?", fa:"آیا بهتر نیست کار دیگری انجام دهیم؟", af:"Moet ons nie liewer iets anders doen nie?" }},
    { de: "Ich habe eine andere Idee.", t:{ ua:"У мене є інша ідея.", tr:"Başka bir fikrim var.", so:"Waxaan hayaa fikrad kale.", fa:"یک ایدهٔ دیگر دارم.", af:"Ek het ’n ander idee." }},
    { de: "Ich habe einen Gegenvorschlag. Wir könnten etwas anderes machen.", t:{ ua:"У мене є зустрічна пропозиція. Ми могли б зробити щось інше.", tr:"Bir karşı önerim var. Başka bir şey yapabiliriz.", so:"Waxaan hayaa soo jeedin ka duwan. Waxaan sameyn karnaa wax kale.", fa:"یک پیشنهاد متقابل دارم. می‌توانیم کار دیگری انجام دهیم.", af:"Ek het ’n teenvoorstel. Ons kan iets anders doen." }},
    { de: "Warum machen wir nicht etwas anderes?", t:{ ua:"Чому б нам не зробити щось інше?", tr:"Neden başka bir şey yapmıyoruz?", so:"Maxaynaan wax kale u sameynin?", fa:"چرا کار دیگری انجام ندهیم؟", af:"Hoekom doen ons nie iets anders nie?" }},
    { de: "Stattdessen schlage ich vor, dass wir etwas anderes machen.", t:{ ua:"Натомість я пропоную зробити щось інше.", tr:"Bunun yerine başka bir şey yapmayı öneriyorum.", so:"Halkii, waxaan soo jeedinayaa inaan wax kale sameyno.", fa:"در عوض پیشنهاد می‌کنم کار دیگری انجام دهیم.", af:"Ek stel eerder voor dat ons iets anders doen." }},
    { de: "Wäre es nicht besser, wenn wir etwas anderes machen?", t:{ ua:"Чи не було б краще зробити щось інше?", tr:"Başka bir şey yapsak daha iyi olmaz mı?", so:"Miyaanay ka fiicnaan lahayn inaan wax kale sameyno?", fa:"آیا بهتر نیست کار دیگری انجام دهیم؟", af:"Sal dit nie beter wees as ons iets anders doen nie?" }},
    { de: "Ich fände es besser, wenn wir etwas anderes machen.", t:{ ua:"Я вважаю, що краще зробити щось інше.", tr:"Başka bir şey yapmamızın daha iyi olacağını düşünüyorum.", so:"Waxaan u arkaa inay ka fiicnaan lahayd inaan wax kale sameyno.", fa:"فکر می‌کنم بهتر است کار دیگری انجام دهیم.", af:"Ek sou dit beter vind as ons iets anders doen." }}
  ],

  add: [
    { de: "Grundsätzlich<br><small>Grundsätzlich finde ich das gut.</small>", t:{ ua:"В принципі / В принципі я вважаю це добрим.", tr:"Genel olarak / Genel olarak bunu iyi buluyorum.", so:"Asal ahaan / Asal ahaan waan u arkaa inay fiicantahay.", fa:"اصولا / اصولا فکر می‌کنم این خوب است.", af:"In beginsel / In beginsel dink ek dit is goed." }},
    { de: "Ehrlich gesagt<br><small>Ehrlich gesagt bin ich nicht sicher.</small>", t:{ ua:"Чесно кажучи / Чесно кажучи, я не впевнений.", tr:"Açıkçası / Açıkçası emin değilim.", so:"Si daacad ah / Si daacad ah ma hubi.", fa:"صادقانه / صادقانه مطمئن نیستم.", af:"Eerlikwaar / Eerlikwaar is ek nie seker nie." }},
    { de: "Im Moment<br><small>Im Moment passt es nicht.</small>", t:{ ua:"Зараз / Зараз не підходить.", tr:"Şu anda / Şu anda uygun değil.", so:"Hadda / Hadda ma shaqeyso.", fa:"در حال حاضر / در حال حاضر مناسب نیست.", af:"Op die oomblik / Op die oomblik pas dit nie." }},
    { de: "Eigentlich<br><small>Eigentlich wollte ich etwas anderes sagen.</small>", t:{ ua:"Власне / Власне я хотів сказати щось інше.", tr:"Aslında / Aslında başka bir şey söylemek istedim.", so:"Dhab ahaan / Dhab ahaan waxaan rabay inaan sheego wax kale.", fa:"در حقیقت / در حقیقت می‌خواستم چیز دیگری بگویم.", af:"Eintlik / Eintlik wou ek iets anders sê." }},
    { de: "Normalerweise<br><small>Normalerweise mache ich das anders.</small>", t:{ ua:"Зазвичай / Зазвичай я роблю це інакше.", tr:"Normalde / Normalde bunu farklı yaparım.", so:"Caadi ahaan / Caadi ahaan waxaan sidan u sameeyaa.", fa:"معمولاً / معمولاً این کار را متفاوت انجام می‌دهم.", af:"Normaalweg / Normaalweg doen ek dit anders." }},
    { de: "Vielleicht<br><small>Vielleicht gibt es eine bessere Lösung.</small>", t:{ ua:"Можливо / Можливо є краще рішення.", tr:"Belki / Belki daha iyi bir çözüm vardır.", so:"Malaha / Malaha waxaa jira xal ka wanaagsan.", fa:"شاید / شاید راه حل بهتری وجود دارد.", af:"Miskien / Miskien is daar 'n beter oplossing." }},
    { de: "Wahrscheinlich<br><small>Wahrscheinlich wird es funktionieren.</small>", t:{ ua:"Ймовірно / Ймовірно це спрацює.", tr:"Muhtemelen / Muhtemelen işe yarayacak.", so:"Malaha / Malaha way shaqeyn doontaa.", fa:"احتمالاً / احتمالا کار خواهد کرد.", af:"Waarskynlik / Waarskynlik sal dit werk." }},
    { de: "Ausserdem<br><small>Ausserdem haben wir keine Zeit.</small>", t:{ ua:"До того ж / До того ж у нас немає часу.", tr:"Ayrıca / Ayrıca zamanımız yok.", so:"Sidoo kale / Sidoo kale ma haysanno waqti.", fa:"علاوه بر این / علاوه بر این وقت نداریم.", af:"Boonop / Boonop het ons nie tyd nie." }},
    { de: "Zudem<br><small>Zudem ist es günstiger.</small>", t:{ ua:"Крім того / Крім того це дешевше.", tr:"Buna ek olarak / Buna ek olarak daha ucuz.", so:"Intaa waxaa dheer / Intaa waxaa dheer waa jaban yahay.", fa:"علاوه بر این / علاوه بر این ارزان‌تر است.", af:"Verder / Verder is dit goedkoper." }},
    { de: "Darüber hinaus<br><small>Darüber hinaus ist es praktischer.</small>", t:{ ua:"Крім того / Крім того це практичніше.", tr:"Bunun ötesinde / Bunun ötesinde daha pratik.", so:"Ka sokow tan / Ka sokow tan waa ka fudud.", fa:"علاوه بر این / علاوه بر این عملی‌تر است.", af:"Daarby / Daarby is dit praktieser." }},
    { de: "Insbesondere<br><small>Insbesondere für Anfänger ist das wichtig.</small>", t:{ ua:"Особливо / Особливо для початківців це важливо.", tr:"Özellikle / Özellikle yeni başlayanlar için bu önemli.", so:"Gaar ahaan / Gaar ahaan bilowga waa muhiim.", fa:"به ویژه / به ویژه برای مبتدی‌ها این مهم است.", af:"Veral / Veral vir beginners is dit belangrik." }},
    { de: "Zwar … aber …<br><small>Zwar ist es teuer, aber es lohnt sich.</small>", t:{ ua:"Хоча … але … / Хоча це дорого, але воно того варте.", tr:"Gerçi … ama … / Gerçi pahalı ama değer.", so:"Inkastoo … laakiin … / Inkastoo qaali tahay, laakiin waa u qalantaa.", fa:"گرچه … اما … / گرچه گران است، اما ارزشش را دارد.", af:"Weliswaar … maar … / Weliswaar is dit duur, maar dit is die moeite werd." }},
    { de: "Jedoch<br><small>Das ist gut, jedoch riskant.</small>", t:{ ua:"Проте / Це добре, проте ризиковано.", tr:"Ancak / Bu iyi, ancak riskli.", so:"Si kastaba ha ahaatee / Tani waa fiican, si kastaba ha ahaatee khatar ah.", fa:"با این حال / این خوب است، با این حال پرخطر است.", af:"Echter / Dit is goed, echter riskant." }},
    { de: "Allerdings<br><small>Allerdings sehe ich ein Problem.</small>", t:{ ua:"Проте / Проте я бачу проблему.", tr:"Ancak / Ancak bir sorun görüyorum.", so:"Si kastaba ha ahaatee / Si kastaba ha ahaatee waxaan arkaa dhibaato.", fa:"البته / البته من یک مشکل می‌بینم.", af:"Echter / Ek sien egter 'n probleem." }},
    { de: "Andererseits<br><small>Andererseits sparen wir Zeit.</small>", t:{ ua:"З іншого боку / З іншого боку ми економимо час.", tr:"Öte yandan / Öte yandan zaman kazanıyoruz.", so:"Dhanka kale / Dhanka kale waqti ayaan badbaadinaynaa.", fa:"از طرف دیگر / از طرف دیگر زمان صرفه‌جویی می‌کنیم.", af:"Aan die ander kant / Aan die ander kant spaar ons tyd." }},
    { de: "Trotzdem<br><small>Trotzdem möchte ich es probieren.</small>", t:{ ua:"Незважаючи на це / Незважаючи на це, я хочу спробувати.", tr:"Yine de / Yine de denemek istiyorum.", so:"Si kastaba / Si kastaba waxaan rabaa inaan isku dayo.", fa:"با این حال / با این حال می‌خواهم امتحان کنم.", af:"Nietemin / Nietemin wil ek dit probeer." }},
    { de: "Daher<br><small>Daher schlage ich vor, dass …</small>", t:{ ua:"Тому / Тому я пропоную, щоб …", tr:"Bundan dolayı / Bundan dolayı öneriyorum ki …", so:"Sidaas darteed / Sidaas darteed waxaan soo jeedinayaa in …", fa:"بنابراین / بنابراین من پیشنهاد می‌کنم که …", af:"Daarom / Daarom stel ek voor dat …" }},
    { de: "Somit<br><small>Somit ist die Entscheidung klar.</small>", t:{ ua:"Таким чином / Таким чином рішення зрозуміле.", tr:"Böylece / Böylece karar net.", so:"Sidaas darteed / Sidaas darteed go'aanka waa cad.", fa:"بنابراین / بنابراین تصمیم واضح است.", af:"Sodoende / Sodoende is die besluit duidelik." }},
    { de: "Letztendlich<br><small>Letztendlich müssen wir entscheiden.</small>", t:{ ua:"Врешті-решт / Врешті-решт ми повинні вирішити.", tr:"Sonuçta / Sonuçta karar vermeliyiz.", so:"Ugu dambeyntii / Ugu dambeyntii waa inaan go'aan gaarno.", fa:"در نهایت / در نهایت باید تصمیم بگیریم.", af:"Uiteindelik / Uiteindelik moet ons besluit neem." }},
    { de: "Ich bin mir nicht ganz sicher, aber …<br><small>Ich bin mir nicht ganz sicher, aber wir könnten es versuchen.</small>", t:{ ua:"Я не зовсім впевнений, але … / Я не зовсім впевнений, але ми могли б спробувати.", tr:"Tam emin değilim ama … / Tam emin değilim ama deneyebiliriz.", so:"Ma hubi laakiin … / Ma hubi laakiin waan isku dayi karnaa.", fa:"کاملاً مطمئن نیستم اما … / کاملاً مطمئن نیستم اما می‌توانیم امتحان کنیم.", af:"Ek is nie heeltemal seker nie, maar … / Ek is nie heeltemal seker nie, maar ons kan dit probeer." }},
    { de: "Ich sehe das ähnlich, aber …<br><small>Ich sehe das ähnlich, aber wir sollten vorsichtig sein.</small>", t:{ ua:"Я бачу це подібно, але … / Я бачу це подібно, але ми повинні бути обережні.", tr:"Benzer düşünüyorum ama … / Benzer düşünüyorum ama dikkatli olmalıyız.", so:"Si la mid ah ayaan u arkaa, laakiin … / Si la mid ah ayaan u arkaa, laakiin waa inaan taxaddar yeelanaa.", fa:"Я бачу це подібно, але … / Я бачу це подібно, але باید محتاط باشیم.", af:"Ek sien dit soortgelyk, maar … / Ek sien dit soortgelyk, maar ons moet versigtig wees." }},
    { de: "Also gut.<br><small>Also gut, machen wir das so.</small>", t:{ ua:"Ну добре / Ну добре, робимо так.", tr:"Peki o zaman / Peki o zaman bunu yapalım.", so:"Hagaag markaa / Hagaag markaa aan sidaas sameyno.", fa:"Добре / Добре, робимо так.", af:"Goed dan / Goed dan, kom ons doen dit so." }},
    { de: "Ist gut so.<br><small>Ja, ist gut so.</small>", t:{ ua:"Так нормально / Так нормально.", tr:"Tamam böyle iyi / Tamam böyle iyi.", so:"Waa hagaag sidan / Waa hagaag sidan.", fa:"Так нормально / Так нормально.", af:"Dis reg so / Dis reg so." }},
    { de: "Passt für mich.<br><small>Ja, passt für mich.</small>", t:{ ua:"Мене влаштовує / Мене влаштовує.", tr:"Benim için uygun / Benim için uygun.", so:"Aniga way ii fiican tahay / Aniga way ii fiican tahay.", fa:"Для мене підходить / Для мене підходить.", af:"Dit werk vir my / Dit werk vir my." }},
    { de: "Das tönt gut.<br><small>Ja, das tönt gut.</small>", t:{ ua:"Звучить добре / Так, звучить добре.", tr:"Kulağa iyi geliyor / Evet, kulağa iyi geliyor.", so:"Si fiican ayey u muuqataa / Haa, si fiican ayey u muuqataa.", fa:"Добре звучить / بله، خوب به نظر می‌رسد.", af:"Dit klink goed / Ja, dit klink goed." }},
    { de: "Mal schauen.<br><small>Mal schauen, wie es läuft.</small>", t:{ ua:"Побачимо / Побачимо, як воно піде.", tr:"Bakalım / Bakalım nasıl gidecek.", so:"Aan aragno / Aan aragno sida ay u socoto.", fa:"Побачимо / ببینیم چگونه پیش می‌رود.", af:"Ons sal sien / Ons sal sien hoe dit verloop." }},
    { de: "Kein Problem.<br><small>Ja, kein Problem.</small>", t:{ ua:"Без проблем / Так, без проблем.", tr:"Sorun değil / Evet, sorun değil.", so:"Dhib ma leh / Haa, dhib ma leh.", fa:"Без проблем / بله، مشکلی نیست.", af:"Geen probleem / Ja, geen probleem." }},
    { de: "Ich kann mir vorstellen, dass das schwierig ist<br><small>Ich kann mir vorstellen, dass das schwierig ist, aber wir schaffen das.</small>", t:{ ua:"Я можу уявити, що це складно / Я можу уявити, що це складно, але ми впораємося.", tr:"Bunun zor olduğunu hayal edebiliyorum / Bunun zor olduğunu hayal edebiliyorum, ama başarabiliriz.", so:"Waxaan qiyaasi karaa inay tani adag tahay / Waxaan qiyaasi karaa inay adag tahay, laakiin waan qaban karnaa.", fa:"می‌توانم تصور کنم که این سخت است / می‌توانم تصور کنم که این سخت است، اما ما موفق می‌شویم.", af:"Ek kan my voorstel dat dit moeilik is / Ek kan my voorstel dat dit moeilik is, maar ons sal dit regkry.", ch:"Ich kann mir vorstellen, dass das schwierig ist / Ich kann mir vorstellen, dass es schwierig ist, aber wir schaffen es." }}
  ],
  
  ask: [
    { de: "Wann passt es dir?", t: { ua: "Коли зручно?", tr: "Ne zaman uygun?", so: "Goorma?", fa: "کی مناسب است؟", af: "Wanneer pas dit?" }},
    { de: "Wo treffen wir uns?", t: { ua: "Де зустрічаємось?", tr: "Nerede?", so: "Xaggee?", fa: "کجا؟", af: "Waar ontmoet ons?" }},
    { de: "Wie lange soll es gehen?", t: { ua: "Як довго?", tr: "Ne kadar?", so: "Intee?", fa: "چقدر؟", af: "Hoe lank?" }},
    { de: "Wer bringt was mit?", t: { ua: "Хто що приносить?", tr: "Kim ne getiriyor?", so: "Yaa maxaa keenaya?", fa: "کی چی می‌آورد؟", af: "Wie bring wat?" }},
    { de: "Mit wem treffen wir uns?", t: { ua: "З ким зустрічаємось?", tr: "Kimle buluşuyoruz?", so: "Kuma la kulmaynaa?", fa: "با کی ملاقات داریم؟", af: "Met wie ontmoet ons?" }},
    { de: "Zu welcher Uhrzeit?", t: { ua: "О котрій годині?", tr: "Saat kaçta?", so: "Waqtigee?", fa: "در چه ساعتی؟", af: "Op watter tyd?" }},
    { de: "An welchem Ort?", t: { ua: "В якому місці?", tr: "Hangi yerde?", so: "Xagee?", fa: "در کجا؟", af: "Op watter plek?" }},
    { de: "Wie viele Personen kommen?", t: { ua: "Скільки людей прийде?", tr: "Kaç kişi gelecek?", so: "Imisa qof ayaa imanaya?", fa: "چند نفر می‌آیند؟", af: "Hoeveel mense kom?" }},
    { de: "Was sollen wir mitbringen?", t: { ua: "Що взяти з собою?", tr: "Ne getirmeliyiz?", so: "Maxaa la keenaa?", fa: "چه چیزی بیاوریم؟", af: "Wat moet ons saambring?" }},
    { de: "Soll ich etwas vorbereiten?", t: { ua: "Мені щось підготувати?", tr: "Bir şey hazırlayayım mı?", so: "Ma diyaariyaa wax?", fa: "چیزی آماده کنم؟", af: "Moet ek iets voorberei?" }},
    { de: "Möchtest du etwas essen?", t: { ua: "Хочеш щось поїсти?", tr: "Bir şey yemek ister misin?", so: "Ma rabtaa wax cunno?", fa: "می‌خوای چیزی بخوری؟", af: "Wil jy iets eet?" }},
    { de: "Brauchen wir Getränke?", t: { ua: "Потрібні напої?", tr: "İçecek lazım mı?", so: "Ma cabitaan baan u baahan nahay?", fa: "نوشیدنی لازم است؟", af: "Het ons drank nodig?" }},
    { de: "Können wir das ändern?", t: { ua: "Можемо це змінити?", tr: "Bunu değiştirebilir miyiz?", so: "Ma beddeli karnaa?", fa: "می‌توانیم تغییر دهیم؟", af: "Kan ons dit verander?" }},
    { de: "Ist das in Ordnung?", t: { ua: "Це нормально?", tr: "Bu uygun mu?", so: "Tani waa hagaag?", fa: "این درست است؟", af: "Is dit reg?" }},
    { de: "Wer übernimmt was?", t: { ua: "Хто що робить?", tr: "Kim ne yapacak?", so: "Yaa maxaa qabanaya?", fa: "کی چه کاری انجام می‌دهد؟", af: "Wie neem wat op?" }},
    { de: "Gibt es ein bestimmtes Datum?", t: { ua: "Є конкретна дата?", tr: "Belirli bir tarih var mı?", so: "Ma jiro taariikh gaar ah?", fa: "تاریخ مشخصی هست؟", af: "Is daar ’n spesifieke datum?" }},
    { de: "Wie sieht der Plan aus?", t: { ua: "Який план?", tr: "Plan nasıl görünüyor?", so: "Maxay qorshuhu u egyahay?", fa: "برنامه چطور است؟", af: "Hoe lyk die plan?" }},
    { de: "Soll es drinnen oder draußen sein?", t: { ua: "Всередині чи на вулиці?", tr: "İçeride mi dışarıda mı?", so: "Ma gudaha mise bannaanka?", fa: "داخل یا بیرون باشد؟", af: "Moet dit binne of buite wees?" }},
    { de: "Welche Kleidung ist passend?", t: { ua: "Який одяг підходить?", tr: "Hangi kıyafet uygun?", so: "Nooca dharka ayaa ku habboon?", fa: "چه لباسی مناسب است؟", af: "Watter klere is gepas?" }},
    { de: "Brauchen wir Tische und Stühle?", t: { ua: "Потрібні столи та стільці?", tr: "Masa ve sandalye lazım mı?", so: "Miisaska iyo kuraasta ma loo baahan yahay?", fa: "به میز و صندلی نیاز داریم؟", af: "Het ons tafels en stoele nodig?" }},
    { de: "Kann jeder kommen?", t: { ua: "Може кожен прийти?", tr: "Herkes gelebilir mi?", so: "Qof walbaa imaan karaa?", fa: "همه می‌توانند بیایند؟", af: "Kan almal kom?" }},
    { de: "Ist es ein privates Treffen?", t: { ua: "Це приватна зустріч?", tr: "Bu özel bir buluşma mı?", so: "Ma kulanka gaarka ah?", fa: "این ملاقات خصوصی است؟", af: "Is dit ’n private ontmoeting?" }},
    { de: "Darf man Gäste mitbringen?", t: { ua: "Можна привести гостей?", tr: "Misafir getirebilir miyiz?", so: "Ma keeni kartaa marti?", fa: "می‌توان مهمان آورد؟", af: "Mag mens gaste saambring?" }},
    { de: "Wie viele Stunden dauert es?", t: { ua: "Скільки годин триватиме?", tr: "Kaç saat sürecek?", so: "Imisa saacadood ayey socon doontaa?", fa: "چند ساعت طول می‌کشد؟", af: "Hoeveel ure duur dit?" }},
    { de: "Welche Getränke gibt es?", t: { ua: "Які напої будуть?", tr: "Hangi içecekler var?", so: "Maxaa cabitaan ah?", fa: "چه نوشیدنی‌هایی هست؟", af: "Watter drankies is daar?" }},
    { de: "Kann ich etwas mitbringen?", t: { ua: "Можу щось принести?", tr: "Bir şey getirebilir miyim?", so: "Ma keeni karaa wax?", fa: "می‌توانم چیزی بیاورم؟", af: "Kan ek iets saambring?" }},
    { de: "Brauchen wir Musik?", t: { ua: "Потрібна музика?", tr: "Müziğe ihtiyaç var mı?", so: "Ma muusig baa loo baahan yahay?", fa: "موسیقی لازم است؟", af: "Het ons musiek nodig?" }},
    { de: "Wie ist das Wetter geplant?", t: { ua: "Яка погода очікується?", tr: "Hava nasıl olacak?", so: "Cimiladu sidee tahay?", fa: "هوا چگونه خواهد بود؟", af: "Hoe lyk die weer?" }},
    { de: "Wer bringt Essen mit?", t: { ua: "Хто принесе їжу?", tr: "Kim yemek getirecek?", so: "Yaa cunto keeni doona?", fa: "چه کسی غذا می‌آورد؟", af: "Wie bring kos saam?" }},
    { de: "Gibt es ein Programm?", t: { ua: "Є програма?", tr: "Bir program var mı?", so: "Ma jiro barnaamij?", fa: "برنامه‌ای هست؟", af: "Is daar ’n program?" }},
    { de: "Müssen wir etwas vorbereiten?", t: { ua: "Потрібно щось підготувати?", tr: "Bir şey hazırlamalı mıyız?", so: "Ma u baahan nahay inaan diyaarinno wax?", fa: "چیزی آماده کنیم؟", af: "Moet ons iets voorberei?" }},
    { de: "Soll ich früh kommen?", t: { ua: "Мені раніше прийти?", tr: "Erken gelmeli miyim?", so: "Ma hore u imaadaa?", fa: "زودتر بیایم؟", af: "Moet ek vroeg kom?" }},
    { de: "Darf ich jemanden einladen?", t: { ua: "Можу когось запросити?", tr: "Birini davet edebilir miyim?", so: "Ma casuumi karaa qof?", fa: "می‌توانم کسی را دعوت کنم؟", af: "Mag ek iemand nooi?" }},
    { de: "Wie viele kommen insgesamt?", t: { ua: "Скільки всього прийде?", tr: "Toplam kaç kişi gelecek?", so: "Imisa qof ayaa guud ahaan imanaya?", fa: "چند نفر کلآ می‌آیند؟", af: "Hoeveel kom in totaal?" }},
    { de: "Können wir vorher sprechen?", t: { ua: "Можемо поговорити заздалегідь?", tr: "Önceden konuşabilir miyiz?", so: "Ma hore u hadli karnaa?", fa: "می‌توانیم قبلاً صحبت کنیم؟", af: "Kan ons vooraf praat?" }},
    { de: "Brauchen wir Snacks?", t: { ua: "Потрібні снеки?", tr: "Atıştırmalık lazım mı?", so: "Ma u baahan nahay cunto fudud?", fa: "به خوراکی نیاز داریم؟", af: "Het ons happies nodig?" }},
    { de: "Soll es formell sein?", t: { ua: "Це має бути офіційно?", tr: "Resmi mi olmalı?", so: "Ma aha rasmi?", fa: "رسمی باشد؟", af: "Moet dit formeel wees?" }},
    { de: "Möchtest du Hilfe?", t: { ua: "Хочеш допомогу?", tr: "Yardım ister misin?", so: "Ma rabtaa caawimo?", fa: "کمک می‌خوای؟", af: "Wil jy hulp hê?" }},
    { de: "Wie sollen wir uns kleiden?", t: { ua: "Як одягнутись?", tr: "Nasıl giyinelim?", so: "Sidee u labisnaa?", fa: "چطور لباس بپوشیم؟", af: "Hoe moet ons aantrek?" }},
    { de: "Soll es drinnen bleiben?", t: { ua: "Залишимо всередині?", tr: "İçeride mi kalsın?", so: "Ma gudaha ha ahaado?", fa: "داخل بماند؟", af: "Moet dit binne bly?" }},
    { de: "Wie viele Kinder kommen?", t: { ua: "Скільки дітей прийде?", tr: "Kaç çocuk gelecek?", so: "Imisa caruur ayaa imanaya?", fa: "چند کودک می‌آیند؟", af: "Hoeveel kinders kom?" }},
    { de: "Brauchen wir Stühle?", t: { ua: "Потрібні стільці?", tr: "Sandalye lazım mı?", so: "Ma u baahan nahay kuraas?", fa: "به صندلی نیاز داریم؟", af: "Het ons stoele nodig?" }},
    { de: "Kann jeder teilnehmen?", t: { ua: "Може кожен брати участь?", tr: "Herkes katılabilir mi?", so: "Qof walbaa ka qayb qaadan karaa?", fa: "همه می‌توانند شرکت کنند؟", af: "Kan almal deelneem?" }},
    { de: "Gibt es besondere Regeln?", t: { ua: "Є особливі правила?", tr: "Özel kurallar var mı?", so: "Ma jiraan xeerar gaar ah?", fa: "قوانین خاصی وجود دارد؟", af: "Is daar spesiale reëls?" }},
    { de: "Wer übernimmt die Organisation?", t: { ua: "Хто організовує?", tr: "Organizasyonu kim üstlenecek?", so: "Yaa qaban doona?", fa: "چه کسی سازماندهی می‌کند؟", af: "Wie neem die organisasie op?" }},
    { de: "Müssen wir etwas kaufen?", t: { ua: "Потрібно щось купити?", tr: "Bir şey almamız gerekiyor mu?", so: "Ma u baahan nahay inaan wax iibsanno?", fa: "چیزی باید بخریم؟", af: "Moet ons iets koop?" }},
    { de: "Was meinst du dazu?", t:{ ua:"Що ти про це думаєш?", tr:"Bu konuda ne düşünüyorsun?", so:"Maxaad ka qabtaa arrintan?", fa:"نظر تو در این مورد چیست؟", af:"Wat dink jy daarvan?" }},
    { de: "Könnte ich meine Meinung äussern?", t:{ ua:"Чи можу я висловити свою думку?", tr:"Fikrimi ifade edebilir miyim?", so:"Ma dhiiban karaa fikradayda?", fa:"می‌توانم نظر خود را بیان کنم؟", af:"Mag ek my mening uitspreek?" }},
    { de: "Wie findest du das?", t:{ ua:"Як тобі це?", tr:"Bunu nasıl buluyorsun?", so:"Sidee u aragtaa tan?", fa:"نظرت دربارهٔ این چیست؟", af:"Hoe vind jy dit?" }},
    { de: "Was hältst du davon?", t:{ ua:"Що ти про це думаєш?", tr:"Bunun hakkında ne düşünüyorsun?", so:"Maxaad ka qabtaa tan?", fa:"دربارهٔ آن چه فکر می‌کنی؟", af:"Wat dink jy daarvan?" }},
    { de: "Was denkst du darüber?", t:{ ua:"Що ти про це думаєш?", tr:"Bunun hakkında ne düşünüyorsun?", so:"Maxaad ka qabtaa arrintan?", fa:"در این باره چه فکر می‌کنی؟", af:"Wat dink jy daaroor?" }}
  ]
};
